#!/usr/bin/env python3
"""Map pinned cpfair annotations onto V20 page tokens without editing Quran text.

Run `python3 tools/build_tajweed_annotations.py` to rebuild and verify the
vendored page annotations. `--verify` checks every generated byte in place.
Only exact Unicode code point matches are projected. Any changed source range
is reported and left plain; this script does not classify Tajweed rules.
"""
import argparse
import collections
import difflib
import hashlib
import json
import unicodedata
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
QURAN = ROOT / 'quran'
SOURCE = ROOT / 'tools' / 'tajweed-source'
OUTPUT = QURAN / 'tajweed'
SOURCE_JSON_SHA = '151d616ad37a4cc21a80f20d5e1104c5b408375107ddd4d71247dea4c05ebf67'
SOURCE_TEXT_SHA = 'c2bfd907f3d353fc9fb27063da5ed471c65717c91b830843880d83eae971c65f'
CURRENT_TEXT_SHA = 'f64fe7657dbe2e185e9995e14f7a67ee6cf1a30773f39184883d7a763d70fb19'
PAGE_BUNDLE_SHA = 'e6e9faa6b3d039347db34f946041e195e071c0105eb5d746e99ace2a2f9c9bed'


def compact(value):
    return json.dumps(value, ensure_ascii=False, separators=(',', ':')) + '\n'


def read_verses(path):
    verses = {}
    for line in path.read_text(encoding='utf-8-sig').splitlines():
        if line and not line.startswith('#'):
            surah, ayah, text = line.split('|', 2)
            key = f'{surah}:{ayah}'
            assert key not in verses
            verses[key] = text
    assert len(verses) == 6236
    return verses


def exact_map(before, after):
    """Map only code points present unchanged in both strings."""
    result = {}
    for kind, i, j, x, y in difflib.SequenceMatcher(
        None, before, after, autojunk=False
    ).get_opcodes():
        if kind == 'equal':
            result.update((i + n, x + n) for n in range(j - i))
    return result


def token_ordinals(text):
    """Return ordinal for each pronounced word code point; pause signs attach left."""
    ordinals = {}
    tokens = []
    cursor = 0
    for part in text.split():
        start = text.find(part, cursor)
        assert start >= cursor
        cursor = start + len(part)
        if any(unicodedata.category(char) == 'Lo' for char in part):
            ordinal = len(tokens)
            tokens.append(part)
        elif set(part) <= set('ۚۖۗۙۘۛۜ') and tokens:
            ordinal = len(tokens) - 1
            tokens[-1] += part
        else:
            assert part in ('۞', '۩'), part
            continue
        for index in range(start, cursor):
            ordinals[index] = ordinal
    return tokens, ordinals


def clusters(text):
    result = []
    for index, char in enumerate(text):
        if unicodedata.category(char).startswith('M') and result:
            result[-1].append(index)
        else:
            result.append([index])
    return result


def page_hash(data):
    material = '\0'.join(
        f'{kind}\1{text}\1{key}'
        for line in data['lines'] for kind, text, key, _ in line
    )
    return hashlib.sha256(material.encode('utf-8')).hexdigest()


def write_or_verify(path, value, verify):
    output = compact(value)
    if verify:
        assert path.read_text(encoding='utf-8') == output, f'Generated file differs: {path}'
    else:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(output, encoding='utf-8')


def build(verify=False):
    for name, expected in [('annotations.json', SOURCE_JSON_SHA),
                           ('quran-uthmani-2017.txt', SOURCE_TEXT_SHA)]:
        assert hashlib.sha256((SOURCE / name).read_bytes()).hexdigest() == expected
    source = read_verses(SOURCE / 'quran-uthmani-2017.txt')
    current = read_verses(QURAN / 'quran-uthmani-v1.1.txt')
    assert hashlib.sha256((QURAN / 'quran-uthmani-v1.1.txt').read_bytes()).hexdigest() == CURRENT_TEXT_SHA
    page_bundle = hashlib.sha256()
    for path in sorted((QURAN / 'pages').glob('*.json')):
        page_bundle.update(path.name.encode('ascii'))
        page_bundle.update(b'\0')
        page_bundle.update(path.read_bytes())
    assert page_bundle.hexdigest() == PAGE_BUNDLE_SHA, 'V2.3 page text or structure changed'
    annotations = json.loads((SOURCE / 'annotations.json').read_text(encoding='utf-8'))
    assert len(annotations) == 6236 and set(source) == set(current)
    assert {(v['surah'], v['ayah']) for v in annotations} == {
        tuple(map(int, key.split(':'))) for key in current
    }
    pages = {}
    verse_items = collections.defaultdict(list)
    for number in range(1, 605):
        page = json.loads((QURAN / 'pages' / f'{number:03}.json').read_text(encoding='utf-8'))
        assert page['page'] == number
        pages[number] = page
        for line_index, line in enumerate(page['lines']):
            for item_index, (kind, text, key, surah) in enumerate(line):
                if kind == 'word':
                    verse_items[key].append((number, line_index, item_index, text))
                elif kind == 'bismillah':
                    verse_items[f'{surah}:1'].append((number, line_index, item_index, text))
    assert len(verse_items) == 6236
    output = collections.defaultdict(lambda: collections.defaultdict(lambda: collections.defaultdict(set)))
    skips = []
    mapped = 0
    exact_verses = 0
    source_rules = collections.Counter()
    for verse in annotations:
        key = f"{verse['surah']}:{verse['ayah']}"
        old, now = source[key], current[key]
        if old == now:
            exact_verses += 1
        items = verse_items[key]
        # The separate basmalah appears before verse words on the page.
        items = sorted(items, key=lambda item: (item[0], item[1], item[2]))
        visible = ' '.join(item[3] for item in items)
        old_to_now = exact_map(old, now)
        now_to_page = exact_map(now, visible)
        old_tokens, old_ordinals = token_ordinals(old)
        now_tokens, now_ordinals = token_ordinals(now)
        page_tokens, page_ordinals = token_ordinals(visible)
        token_count_match = len(old_tokens) == len(now_tokens) == len(page_tokens)
        positions = {}
        offset = 0
        for number, line, item, text in items:
            for index in range(len(text)):
                positions[offset + index] = (number, line, item, index)
            offset += len(text) + 1
        for annotation in verse['annotations']:
            rule = annotation['rule']
            source_rules[rule] += 1
            start, end = annotation['start'], annotation['end']
            reason = None
            if not (0 <= start < end <= len(old)):
                reason = 'invalid_source_bounds'
            elif not token_count_match:
                reason = 'changed_word_boundaries'
            else:
                indices = [old_to_now.get(index) for index in range(start, end)]
                if None in indices or indices != list(range(indices[0], indices[0] + len(indices))):
                    reason = 'changed_source_range'
                elif any(old_ordinals.get(a) != now_ordinals.get(b) for a, b in zip(range(start, end), indices)):
                    reason = 'ambiguous_word_alignment'
                else:
                    target = [now_to_page.get(index) for index in indices if not now[index].isspace()]
                    if not target or None in target or any(index not in positions for index in target):
                        reason = 'page_projection_gap'
                    elif any(now_ordinals.get(a) != page_ordinals.get(b)
                             for a, b in zip((index for index in indices if not now[index].isspace()), target)):
                        reason = 'ambiguous_page_alignment'
            if reason:
                skips.append({'verse': key, 'rule': rule, 'start': start, 'end': end, 'reason': reason})
                continue
            mapped += 1
            for index in target:
                number, line, item, char = positions[index]
                output[number][(line, item)][char].add(rule)

    conflict_clusters = 0
    reconstructed_tokens = 0
    final_rules = collections.Counter()
    page_outputs = {}
    for number, page in pages.items():
        entries = []
        for (line, item), chars in sorted(output[number].items()):
            kind, text, _, _ = page['lines'][line][item]
            assert kind in ('word', 'bismillah')
            assignments = [set() for _ in text]
            for index, rules in chars.items():
                assignments[index].update(rules)
            # Colour complete graphemes so Arabic diacritics never detach.
            for cluster in clusters(text):
                rules = set().union(*(assignments[index] for index in cluster))
                if len(rules) > 1:
                    conflict_clusters += 1
                    rules = set()
                for index in cluster:
                    assignments[index] = rules
            segments = []
            begin = 0
            while begin < len(text):
                rules = assignments[begin]
                end = begin + 1
                while end < len(text) and assignments[end] == rules:
                    end += 1
                if rules:
                    rule = next(iter(rules))
                    segments.append([begin, end, rule])
                    final_rules[rule] += 1
                begin = end
            if segments:
                assert all(0 <= a < b <= len(text) for a, b, _ in segments)
                pieces = []
                previous = 0
                for start, end, _ in segments:
                    assert start >= previous
                    pieces.extend((text[previous:start], text[start:end]))
                    previous = end
                pieces.append(text[previous:])
                assert ''.join(pieces) == text
                reconstructed_tokens += 1
                entries.append([line, item, segments])
        result = {'page': number, 'textHash': page_hash(page), 'tokens': entries}
        page_outputs[number] = result
        write_or_verify(OUTPUT / 'pages' / f'{number:03}.json', result, verify)
    report = {
        'source': 'cpfair/quran-tajweed 496f71cd191da00fa2a37ded79dbbddb033bb0ad',
        'sourceAnnotationSha256': SOURCE_JSON_SHA,
        'sourceTextSha256': SOURCE_TEXT_SHA,
        'currentTextSha256': CURRENT_TEXT_SHA,
        'v23PageBundleSha256': PAGE_BUNDLE_SHA,
        'surahs': 114, 'verses': len(annotations), 'pages': len(pages),
        'exactSourceVerses': exact_verses,
        'changedSourceVerses': len(annotations) - exact_verses,
        'nfcExactSourceVerses': sum(
            unicodedata.normalize('NFC', source[key]) == unicodedata.normalize('NFC', current[key])
            for key in current
        ),
        'versesWithUnmappedAnnotations': len({item['verse'] for item in skips}),
        'sourceCodepoints': sum(map(len, source.values())),
        'currentCodepoints': sum(map(len, current.values())),
        'sourcePauseMarks': sum(sum(char in 'ۚۖۗۙۘۛۜ' for char in text) for text in source.values()),
        'currentPauseMarks': sum(sum(char in 'ۚۖۗۙۘۛۜ' for char in text) for text in current.values()),
        'sourceTatweel': sum(text.count('ـ') for text in source.values()),
        'currentTatweel': sum(text.count('ـ') for text in current.values()),
        'sourceAnnotations': sum(source_rules.values()),
        'mappedAnnotations': mapped,
        'skippedAnnotations': len(skips),
        'skipReasons': dict(collections.Counter(item['reason'] for item in skips)),
        'conflictingGraphemeClustersLeftPlain': conflict_clusters,
        'annotatedTokensReconstructedExactly': reconstructed_tokens,
        'renderedSegmentsByRule': dict(sorted(final_rules.items())),
        'sourceAnnotationsByRule': dict(sorted(source_rules.items())),
        'unmapped': skips,
    }
    assert report['sourceAnnotations'] == mapped + len(skips)
    write_or_verify(OUTPUT / 'alignment-report.json', report, verify)
    print(f"PASS: {len(annotations)} verses, {len(pages)} pages, {mapped:,} exact annotations mapped, "
          f"{len(skips):,} reported skips, {conflict_clusters} conflicting graphemes left plain")
    return report


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--verify', action='store_true')
    build(parser.parse_args().verify)
