const {chromium}=require('playwright'),assert=require('assert'),fs=require('fs'),path=require('path');
const url=process.env.QURAN_QA_URL||'http://127.0.0.1:8826/',out=process.env.QURAN_QA_OUTPUT||'/Users/halimi_hanim/Projects/Islamic-App-QA-V2.6.2',key='uwa-quran-recent-v1';fs.mkdirSync(out,{recursive:true});
const history=p=>p.evaluate(key=>JSON.parse(localStorage.getItem(key)).entries,key);
const ready=p=>p.waitForFunction(()=>document.querySelector('#quran-reader-status').textContent===''&&!!document.querySelector('#quran-verse-list .quran-verse, #quran-mushaf-page .quran-page-folio, #quran-classic-page .quran-page-folio'));
async function library(p){await p.locator('[data-app-view="allday"]').click();if(await p.locator('#quran-reader').isVisible())await p.locator('#quran-back').click();await p.locator('#quran-tab-library').click();await p.waitForFunction(()=>document.querySelectorAll('#quran-surah-list button').length===114);}
async function open(p,n){await p.locator('#quran-search').fill('');await p.locator('#quran-surah-list [data-surah="'+n+'"]').click();await ready(p);}
(async()=>{
 const b=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true}),results=[];
 for(const width of [320,390,1280]){
  const ctx=await b.newContext({viewport:{width,height:844},hasTouch:width<600,isMobile:width<600,timezoneId:'Asia/Kuala_Lumpur',serviceWorkers:'block'}),p=await ctx.newPage(),errors=[],requests=[];
  p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error')errors.push(m.text())});p.on('request',r=>requests.push(r.url()));
  await p.addInitScript(()=>{window.recentWrites=0;const set=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k==='uwa-quran-recent-v1')window.recentWrites++;return set.call(this,k,v)}});
  await p.goto(url);await library(p);assert.deepEqual(await history(p),[]);assert(await p.locator('#quran-recent-empty').isVisible());assert(!requests.some(u=>/\/quran\/(?:pages|surah|scripts\/simple\/surah)\//.test(u)));await p.screenshot({path:`${out}/empty-${width}.png`,fullPage:false});
  await p.locator('#quran-search').fill('Fatihah');assert.deepEqual(await history(p),[]);await p.locator('#quran-search').fill('');
  await open(p,2);assert.deepEqual((await history(p)).map(x=>x.surah),[2]);await p.locator('#quran-back').click();await p.screenshot({path:`${out}/one-${width}.png`,fullPage:false});
  // Direct browsing retains first-ayah behavior. Actual wheel reading saves a stable visible identity.
  await open(p,2);const before=await p.evaluate(()=>window.recentWrites);await p.locator('#quran-ayah-20').evaluate(e=>e.scrollIntoView({block:'start',behavior:'instant'}));assert.equal((await history(p))[0].ayah,1,'programmatic scroll is not reading');
  await p.mouse.move(width/2,300);await p.mouse.wheel(0,30);await p.waitForFunction(()=>JSON.parse(localStorage.getItem('uwa-quran-recent-v1')).entries[0].ayah>1);
  const saved=(await history(p))[0].ayah;assert(saved>=19&&saved<=21,'stable visible ayah near20');assert.equal(await p.evaluate(()=>window.recentWrites)-before,1,'one scroll write');
  await p.locator('#quran-back').click();await p.locator('[data-recent-surah="2"]').click();await ready(p);await p.waitForFunction(ayah=>{const r=document.querySelector('#quran-ayah-'+ayah).getBoundingClientRect();return r.top>=70&&r.top<130},saved);assert.equal((await history(p))[0].ayah,saved);await p.screenshot({path:`${out}/list-resume-${width}.png`,fullPage:false});
  // Pending scroll flush before capture-phase application navigation.
  await p.locator('#quran-ayah-30').evaluate(e=>e.scrollIntoView({block:'start',behavior:'instant'}));await p.evaluate(()=>{window.dispatchEvent(new WheelEvent('wheel',{deltaY:1}));for(let i=0;i<100;i++)window.dispatchEvent(new Event('scroll'))});const pendingBefore=await p.evaluate(()=>window.recentWrites);if(width<600)await p.locator('#quran-back').click();else await p.locator('[data-app-view="home"]').evaluate(e=>e.click());assert((await history(p))[0].ayah>=29);assert(await p.evaluate(()=>window.recentWrites)-pendingBefore<=1,'flush does not spam');
  await library(p);await open(p,2);assert.equal((await history(p))[0].ayah,1,'ordinary direct open resets to first ayah');
  // Pending visibility and pagehide flush, not relying solely on unload.
  await p.locator('#quran-ayah-40').evaluate(e=>e.scrollIntoView({block:'start',behavior:'instant'}));await p.evaluate(()=>{window.dispatchEvent(new WheelEvent('wheel'));window.dispatchEvent(new Event('scroll'));Object.defineProperty(document,'hidden',{configurable:true,get:()=>true});document.dispatchEvent(new Event('visibilitychange'))});assert((await history(p))[0].ayah>=39);await p.evaluate(()=>{delete document.hidden});
  await p.locator('#quran-ayah-50').evaluate(e=>e.scrollIntoView({block:'start',behavior:'instant'}));await p.evaluate(()=>{window.dispatchEvent(new WheelEvent('wheel'));window.dispatchEvent(new Event('scroll'));window.dispatchEvent(new Event('pagehide'))});assert((await history(p))[0].ayah>=49);await p.locator('#quran-back').click();
  // Reopen/dedup/cap, including a long Latin name. Record only actual open events.
  for(const n of [60,90,91,92,93,94,95,96,97,98,99]){await open(p,n);await p.locator('#quran-back').click()}
  let entries=await history(p);assert.equal(entries.length,10);assert.deepEqual(entries.map(x=>x.surah),[99,98,97,96,95,94,93,92,91,90]);await open(p,60);await p.locator('#quran-back').click();entries=await history(p);assert.deepEqual(entries.map(x=>x.surah),[60,99,98,97,96,95,94,93,92,91]);await open(p,95);await p.locator('#quran-back').click();assert.equal((await history(p)).length,10);assert.equal((await history(p))[0].surah,95);
  const row=p.locator('#quran-recent-row');assert.equal(await p.locator('.quran-recent-item').count(),10);
  const geometry=await row.evaluate(e=>({tops:[...e.children].map(x=>x.getBoundingClientRect().top),scroll:e.scrollWidth,width:e.clientWidth,doc:document.documentElement.scrollWidth-innerWidth}));assert.equal(new Set(geometry.tops).size,1);assert(geometry.scroll>geometry.width&&geometry.doc<=1);await p.screenshot({path:`${out}/ten-${width}.png`,fullPage:false});
  await p.locator('.quran-recent-item').first().focus();for(let i=0;i<9;i++)await p.keyboard.press('Tab');assert.equal(await p.evaluate(()=>document.activeElement.dataset.recentSurah),String((await history(p))[9].surah));assert(await row.evaluate(e=>e.scrollLeft)>0,'keyboard brings offscreen entry into view');
  await row.evaluate(e=>e.scrollLeft=0);const frame=await row.boundingBox();await p.mouse.move(frame.x+30,frame.y+30);await p.mouse.wheel(0,250);await p.waitForFunction(()=>document.querySelector('#quran-recent-row').scrollLeft>0);
  let nativeSwipe=false;
  if(width<600){await row.evaluate(e=>e.scrollLeft=0);const cdp=await ctx.newCDPSession(p),rect=await row.boundingBox(),x=rect.x+rect.width-20,y=rect.y+30;await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y,id:0}]});for(let i=1;i<=5;i++)await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x-i*(rect.width-40)/5,y,id:0}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await p.waitForFunction(()=>document.querySelector('#quran-recent-row').scrollLeft>0);nativeSwipe=true;await cdp.detach()}
  await row.evaluate(e=>e.scrollLeft=0);await p.locator('#quran-search').focus();
  const snapshot=JSON.stringify(await history(p));await p.locator('#quran-tab-routine').click();await p.locator('#quran-add').click();assert(await p.locator('#quran-recent').isHidden());await p.locator('[data-surah="3"]').click();await p.locator('#quran-selection-done').click();await p.locator('#allday-checklist [data-zikir-id="112"] input').check();await p.locator('[data-sort="allday"]').click();const h=p.locator('#allday-checklist .drag-handle').first();await h.focus();await p.keyboard.press('Space');await p.keyboard.press('ArrowDown');await p.keyboard.press('Enter');await p.locator('[data-sort="allday"]').click();assert.equal(JSON.stringify(await history(p)),snapshot,'management does not create history');
  await p.locator('#allday-checklist [data-zikir-id="3"] .checklist-name').click();await ready(p);assert.equal((await history(p))[0].surah,3);await p.locator('#quran-back').click();assert(await p.locator('#quran-routine').isVisible());
  const preserved=await history(p);await p.reload();await library(p);assert.deepEqual(await history(p),preserved);await p.clock.install({time:new Date(Date.now()+86400000)});await p.evaluate(()=>window.dispatchEvent(new Event('focus')));assert.deepEqual(await history(p),preserved,'history never resets daily');
  assert.deepEqual(errors,[]);results.push({width,zeroOneTen:true,listScrollResume:true,pendingFlush:true,dedupCap:true,noManagementHistory:true,keyboardWheel:true,nativeSwipe,sourceRequestsAtStartup:0,errors:0});await ctx.close();console.log('passed width',width);
 }
 // Both page renderers: genuine cross-surah navigation and multi-surah retention.
 const ctx=await b.newContext({viewport:{width:390,height:844},serviceWorkers:'block'}),p=await ctx.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(url);
 const pageCases=[];
 for(const mode of ['page','classic']){
  await p.evaluate(({key,mode})=>{localStorage.setItem(key,JSON.stringify({schema:1,entries:[{surah:113,ayah:1,page:604,mode}]}));localStorage.setItem('uwa-quran-reader-v1',JSON.stringify({mode,script:'uthmani',uthmaniMode:mode,last:{surah:1,ayah:1,page:1,mode:'list'},bookmarks:['1:2']}));localStorage.setItem('uwa-quran-tajweed-v1','on')},{key,mode});await p.reload();await library(p);await p.locator('[data-recent-surah="113"]').click();await ready(p);assert.deepEqual((await history(p)).map(x=>x.surah),[113]);assert.equal((await history(p))[0].page,604);await p.evaluate(()=>document.fonts.ready);
  await p.locator(`#quran-prev-${mode==='page'?'page':'classic'}-bottom`).click();await p.waitForFunction(()=>JSON.parse(localStorage.getItem('uwa-quran-recent-v1')).entries[0].page===603);assert.equal((await history(p))[0].surah,109,'canonical first boundary on603');
  await p.locator(`#quran-next-${mode==='page'?'page':'classic'}-bottom`).click();await p.waitForFunction(()=>JSON.parse(localStorage.getItem('uwa-quran-recent-v1')).entries[0].page===604);assert.equal((await history(p))[0].surah,112);assert.deepEqual((await history(p)).map(x=>x.surah),[112,109,113]);assert(!(await history(p)).some(x=>x.surah===114),'no phantom offscreen surah');
  const before=JSON.stringify(await history(p));const writes=await p.evaluate(()=>{window.qawrites=0;const set=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k==='uwa-quran-recent-v1')window.qawrites++;return set.call(this,k,v)}});await p.locator('#quran-settings-toggle').click();await p.locator('#quran-tajweed-off').click();await p.locator('#quran-tajweed-on').click();await p.locator('#quran-settings-close').click();await p.evaluate(()=>window.dispatchEvent(new Event('resize')));assert.equal(JSON.stringify(await history(p)),before);assert.equal(await p.evaluate(()=>window.qawrites),0,'preference rendering and fitting no history writes');
  await p.locator('#quran-back').click();await p.locator('[data-recent-surah="113"]').click();await ready(p);assert.equal((await history(p))[0].surah,113);assert.equal((await history(p))[0].page,604);await p.locator('#quran-back').click();assert.equal(await p.evaluate(()=>document.activeElement.dataset.recentSurah),'113');pageCases.push({mode,multiSurahRetained:true,forwardBackward:true,resumeFocus:true,noLayoutHistory:true});
 }
 // Global script/Tajweed never overwritten by stored history mode.
 await p.evaluate(key=>{localStorage.setItem(key,JSON.stringify({schema:1,entries:[{surah:112,ayah:1,page:604,mode:'classic'}]}));localStorage.setItem('uwa-quran-reader-v1',JSON.stringify({mode:'list',script:'simple',uthmaniMode:'classic',bookmarks:['1:2']}));localStorage.setItem('uwa-quran-tajweed-v1','on')},key);await p.reload();await library(p);await p.locator('[data-recent-surah="112"]').click();await p.waitForFunction(()=>document.querySelector('#quran-mushaf-page .quran-simple-verse')&&document.querySelector('#quran-reader-status').textContent==='');assert(await p.locator('#quran-classic-panel').isHidden());assert.equal(await p.evaluate(()=>JSON.parse(localStorage.getItem('uwa-quran-reader-v1')).script),'simple');assert.equal(await p.evaluate(()=>localStorage.getItem('uwa-quran-tajweed-v1')),'on');assert.deepEqual(await p.evaluate(()=>JSON.parse(localStorage.getItem('uwa-quran-reader-v1')).bookmarks),['1:2']);assert.equal((await history(p)).length,1);assert.equal((await history(p))[0].mode,'page');
 await p.locator('#quran-settings-toggle').click();await p.locator('#quran-script-uthmani').click();await p.waitForFunction(()=>!document.querySelector('#quran-classic-panel').hidden&&document.querySelector('#quran-reader-status').textContent==='');assert.equal((await history(p)).length,1);await p.locator('#quran-list-mode').click();await p.waitForFunction(()=>document.querySelectorAll('#quran-verse-list .quran-verse').length===4);await p.locator('#quran-settings-close').click();const bookmark=p.locator('[data-bookmark="112:2"]');await bookmark.click();assert.equal(await bookmark.getAttribute('aria-pressed'),'true');assert((await p.evaluate(()=>JSON.parse(localStorage.getItem('uwa-quran-reader-v1')).bookmarks)).includes('112:2'));
 // Storage refusal leaves reading usable and existing persisted history unchanged.
 const stored=await p.evaluate(key=>localStorage.getItem(key),key);await p.evaluate(key=>{const set=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k===key)throw Error('synthetic failure');return set.call(this,k,v)}},key);await p.locator('#quran-back').click();await open(p,114);assert.equal(await p.locator('#quran-reader-title').textContent(),'An-Nas');assert.equal(await p.evaluate(key=>localStorage.getItem(key),key),stored);await p.locator('#quran-back').click();assert.match(await p.locator('#quran-recent-status').textContent(),/belum dapat disimpan/);assert.deepEqual(errors,[]);
 await ctx.close();await b.close();const report={widths:results,pageCases,compatibilityBookmarks:true,writeFailureReadingUsable:true,physicalIPhoneTested:false};fs.writeFileSync(out+'/recent-interactions.json',JSON.stringify(report,null,2));console.log('PASS',JSON.stringify(report));
})().catch(e=>{console.error(e);process.exit(1)});
