const {chromium}=require('playwright'),assert=require('assert'),fs=require('fs'),path=require('path');const root=path.resolve(__dirname,'..'),out=process.env.QURAN_QA_OUTPUT||'/Users/halimi_hanim/Projects/Islamic-App-QA-V2.6.3',url=process.env.QURAN_QA_URL||'http://127.0.0.1:8826/',key='uwa-quran-reader-v1';
(async()=>{const b=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});try{
const c=await b.newContext({viewport:{width:390,height:844},serviceWorkers:'block'}),p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error')errors.push(m.text())});await p.goto(url);await p.evaluate(key=>localStorage.setItem(key,JSON.stringify({bookmarks:['28:3'],script:'uthmani',mode:'list'})),key);await p.reload();let release;const gate=new Promise(r=>release=r);await p.route('**/quran/surah/028.json',async route=>{await gate;await route.continue()});await p.locator('[data-app-view="allday"]').click();await p.locator('.quran-favourite-loading').waitFor();await p.locator('#quran-tab-library').click();await p.locator('[data-surah="1"]').click();await p.waitForFunction(()=>document.querySelectorAll('#quran-verse-list .quran-verse').length===7);await p.locator('#quran-settings-toggle').click();await p.locator('#quran-script-simple').click();await p.waitForFunction(()=>document.querySelector('#quran-script-simple').getAttribute('aria-pressed')==='true'&&document.querySelector('#quran-reader-status').textContent==='');await p.locator('#quran-settings-close').click();await p.locator('#quran-back').click();await p.locator('#quran-tab-routine').click();release();await p.waitForFunction(()=>document.querySelector('[data-favourite="28:3"] .quran-verse-arabic'));const simple=JSON.parse(fs.readFileSync(root+'/quran/scripts/simple/surah/028.json'));assert.equal(await p.locator('[data-favourite="28:3"] .quran-verse-arabic').innerText(),simple.verses[2][1]);await p.unroute('**/quran/surah/028.json');await p.locator('#quran-favourites').evaluate(e=>scrollTo({top:scrollY+e.getBoundingClientRect().top-25,behavior:'instant'}));await p.screenshot({path:out+'/favourites-one-390.png',fullPage:false});
// Removal refusal retains the entry, keyboard Enter opens exact ayah.
await p.evaluate(()=>{window.qaSet=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k==='uwa-quran-reader-v1')throw Error();return window.qaSet.call(this,k,v)}});await p.locator('[data-favourite-remove="28:3"]').click();assert.equal(await p.locator('[data-favourite="28:3"]').count(),1);assert.match(await p.locator('#quran-favourites-status').innerText(),/gagal/);await p.evaluate(()=>Storage.prototype.setItem=window.qaSet);await p.locator('[data-favourite-open="28:3"]').focus();await p.keyboard.press('Enter');await p.waitForFunction(()=>document.querySelector('#quran-ayah-3')?.getBoundingClientRect().top>=70&&document.querySelector('#quran-ayah-3')?.getBoundingClientRect().top<130);await p.locator('#quran-back').click();await p.waitForFunction(()=>document.activeElement?.dataset.favouriteOpen==='28:3');await p.keyboard.press('Tab');assert.equal(await p.evaluate(()=>document.activeElement.dataset.favouriteRemove),'28:3');await p.keyboard.press('Enter');assert.equal(await p.locator('.quran-favourite').count(),0);assert.equal(await p.evaluate(()=>document.activeElement.id),'quran-favourites-title');
// Missing source translation is omitted without substitution.
await p.evaluate(key=>{const d=JSON.parse(localStorage.getItem(key));d.bookmarks=['9:1'];d.script='uthmani';localStorage.setItem(key,JSON.stringify(d))},key);await p.reload();await p.route('**/quran/surah/009.json',async route=>{const data=JSON.parse(fs.readFileSync(root+'/quran/surah/009.json'));data.verses[0][2]=null;await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(data)})});await p.locator('[data-app-view="allday"]').click();await p.waitForFunction(()=>document.querySelector('[data-favourite="9:1"] .quran-verse-arabic'));assert.equal(await p.locator('[data-favourite="9:1"] .quran-verse-translation').count(),0);await p.unroute('**/quran/surah/009.json');
// Multi-tab collection freshness: a reader preference/position save cannot restore removed bookmarks.
await p.locator('[data-favourite-open="9:1"]').click();await p.waitForFunction(()=>document.querySelectorAll('#quran-verse-list .quran-verse').length===129);const n=await c.newPage();await n.goto(url);await n.locator('[data-app-view="allday"]').click();await n.locator('[data-favourite-remove="9:1"]').click();await p.waitForFunction(()=>document.querySelector('[data-bookmark="9:1"]').getAttribute('aria-pressed')==='false');await p.locator('#quran-ayah-2 .quran-verse-arabic').click();assert.deepEqual(await p.evaluate(key=>JSON.parse(localStorage.getItem(key)).bookmarks,key),[]);await c.close();
// First and last valid ayah navigation is readable at each width.
for(const width of [320,390,1280]){const c=await b.newContext({viewport:{width,height:844},serviceWorkers:'block'}),p=await c.newPage();await p.goto(url);await p.evaluate(key=>localStorage.setItem(key,JSON.stringify({bookmarks:['1:1','114:6','2:286'],script:'uthmani',mode:'page'})),key);await p.reload();await p.locator('[data-app-view="allday"]').click();for(const ref of ['1:1','114:6','2:286']){const[s,a]=ref.split(':').map(Number);await p.locator(`[data-favourite-open="${ref}"]`).click();await p.waitForFunction(a=>{const r=document.querySelector('#quran-ayah-'+a)?.getBoundingClientRect();return r&&r.top>=64&&r.top<innerHeight-120},a);assert.equal(await p.locator('#quran-reader-title').innerText(),JSON.parse(fs.readFileSync(root+'/quran/chapters.json'))[s-1][1]);await p.locator('#quran-back').click();await p.waitForFunction(ref=>document.activeElement?.dataset.favouriteOpen===ref,ref)}await c.close()}
assert.deepEqual(errors,[]);fs.writeFileSync(out+'/favourites-edges.json',JSON.stringify({rapidScriptDuringPendingLoad:true,removalRefusal:true,keyboardOpenRemoveFocus:true,missingTranslationOmitted:true,multiTabLatestBookmarksPreserved:true,firstLastHeaderSafe:[320,390,1280],errors},null,2));console.log('PASS favourites edge cases')
}finally{await b.close()}})().catch(e=>{console.error(e);process.exit(1)});
