// V2.5.2: immutable QCF identities, rendered full-page fit, glyph/marker bounds,
// largest-fit representative checks, per-page metrics and distributions.
const {chromium}=require('playwright'),fs=require('fs'),path=require('path'),assert=require('assert');
const root=path.resolve(__dirname,'..'),url=process.env.QURAN_QA_URL||'http://127.0.0.1:8821/',out=process.env.QURAN_QA_OUTPUT||'/private/tmp/v252-qa';fs.mkdirSync(out,{recursive:true});
const widths=(process.env.QURAN_QA_WIDTHS||'320,390').split(',').map(Number),reps=[1,7,12,303,420,534,535,597,604],chapters=JSON.parse(fs.readFileSync(path.join(root,'quran/chapters.json'))),json=p=>JSON.parse(fs.readFileSync(path.join(root,p)));
const classes={ghunnah:'ghunnah',hamzat_wasl:'silent',lam_shamsiyyah:'silent',silent:'silent',idghaam_ghunnah:'idgham',idghaam_no_ghunnah:'idgham',idghaam_mutajanisayn:'idgham',idghaam_mutaqaribayn:'idgham',idghaam_shafawi:'idgham',ikhfa:'ikhfa',ikhfa_shafawi:'ikhfa',iqlab:'iqlab',qalqalah:'qalqalah',madd_2:'madd',madd_246:'madd',madd_6:'madd',madd_munfasil:'madd',madd_muttasil:'madd'};
const arabic=n=>String(n).replace(/\d/g,d=>'٠١٢٣٤٥٦٧٨٩'[+d]);
const ready=(p,n)=>p.waitForFunction(n=>document.querySelector('#quran-classic-page').dataset.fitReady==='true'&&document.querySelector('#quran-classic-page .quran-page-folio')?.textContent===String(n).replace(/\d/g,d=>'٠١٢٣٤٥٦٧٨٩'[+d])&&document.querySelector('#quran-reader-status').textContent==='',n);
async function measure(p){return p.evaluate(()=>{const s=document.querySelector('#quran-classic-page'),st=getComputedStyle(s),r=s.getBoundingClientRect(),top=r.top+parseFloat(st.borderTopWidth)+parseFloat(st.paddingTop),innerHeight=r.height-parseFloat(st.borderTopWidth)-parseFloat(st.borderBottomWidth)-parseFloat(st.paddingTop)-parseFloat(st.paddingBottom),contentHeight=Math.max(...[...s.children].map(e=>e.getBoundingClientRect().bottom+parseFloat(getComputedStyle(e).marginBottom)-top)),words=[...s.querySelectorAll('.quran-page-word')],markers=[...s.querySelectorAll('.quran-verse-marker')],canvas=document.createElement('canvas').getContext('2d'),escapes=[];
for(const e of [...words,...markers]){const b=e.getBoundingClientRect();let left=b.left,right=b.right,bottom=b.bottom,et=b.top;if(e.matches('.quran-verse-marker')){left-=2;right+=2;bottom+=2;et-=2}else{const c=getComputedStyle(e);canvas.font=`${c.fontWeight} ${c.fontSize} ${c.fontFamily}`;canvas.direction='rtl';canvas.textAlign='right';const ink=canvas.measureText(e.textContent);left=Math.min(left,b.right-ink.actualBoundingBoxLeft);right=Math.max(right,b.right+ink.actualBoundingBoxRight)}if(left<r.left+1||right>r.right-1||bottom>r.bottom-1||et<r.top+1)escapes.push(e.textContent)}
return{font:parseFloat(getComputedStyle(s.querySelector('.quran-classic-line:not(.quran-page-heading):not(.quran-page-bismillah)')).fontSize),containerHeight:r.height,innerHeight,contentHeight,sparePercent:100*(1-contentHeight/innerHeight),horizontalOverflow:s.scrollWidth-s.clientWidth,verticalOverflow:s.scrollHeight-s.clientHeight,documentOverflow:document.documentElement.scrollWidth-innerWidth,viewportHeight:window.innerHeight,screenHeight:document.documentElement.scrollHeight,words:words.map(e=>e.textContent),lines:[...s.querySelectorAll('.quran-classic-line')].map(e=>[...e.children].flatMap(x=>x.classList.contains('quran-classic-end-pair')?[...x.children]:[x]).map(x=>x.textContent)),markers:markers.map(e=>e.getAttribute('aria-label').replace('Akhir ayat ','')),colours:[...s.querySelectorAll('[class^="tajweed-"]')].map(e=>[e.className,e.textContent,getComputedStyle(e).color,getComputedStyle(e).getPropertyValue('--'+e.className).trim()]),quarters:s.querySelectorAll('.quran-page-quarter').length,sajdah:s.querySelectorAll('.quran-page-sajdah').length,escapes,pairedMarkers:markers.every(e=>{const pair=e.closest('.quran-classic-end-pair');return pair&&pair.querySelector('.quran-page-word')&&Math.abs(pair.querySelector('.quran-page-word').getBoundingClientRect().top-e.getBoundingClientRect().top)<parseFloat(getComputedStyle(pair).fontSize)*2})}})}
// Independently exhaustively try every larger quarter-pixel body size on
// representatives. The production fitter uses binary search, not this loop.
async function assertLargest(p,selected){const largerFit=await p.evaluate(selected=>{const s=document.querySelector('#quran-classic-page'),lines=[...s.querySelectorAll('.quran-classic-line')],ordinary=lines.filter(e=>!e.matches('.quran-page-heading,.quran-page-bismillah')),structural=lines.filter(e=>!ordinary.includes(e)),old=lines.map(e=>e.style.fontSize),oldBody=s.style.getPropertyValue('--classic-font-size'),st=getComputedStyle(s),r=s.getBoundingClientRect(),top=r.top+parseFloat(st.borderTopWidth)+parseFloat(st.paddingTop),limit=(r.height-parseFloat(st.borderTopWidth)-parseFloat(st.borderBottomWidth)-parseFloat(st.paddingTop)-parseFloat(st.paddingBottom))*.97;
const caps=structural.map(e=>{let cap=13;for(let size=13;size<=24;size+=.25){e.style.fontSize=size+'px';if(e.scrollWidth<=e.clientWidth)cap=size}return cap});let fit=null;
for(let size=selected+.25;size<=28;size+=.25){s.style.setProperty('--classic-font-size',size+'px');ordinary.forEach(e=>e.style.fontSize=size+'px');structural.forEach((e,i)=>e.style.fontSize=Math.min(caps[i],size+2)+'px');const content=Math.max(...[...s.children].map(e=>e.getBoundingClientRect().bottom+parseFloat(getComputedStyle(e).marginBottom)-top));if(content<=limit&&[...s.querySelectorAll('.quran-classic-section,.quran-page-heading,.quran-page-bismillah')].every(e=>e.scrollWidth<=e.clientWidth)){fit=size;break}}
lines.forEach((e,i)=>e.style.fontSize=old[i]);s.style.setProperty('--classic-font-size',oldBody);return fit},selected);assert.equal(largerFit,null,'largest safe font '+selected)}
function stats(values){const a=[...values].sort((a,b)=>a-b),q=p=>a[Math.floor((a.length-1)*p)];return{min:a[0],p10:q(.1),median:q(.5),p90:q(.9),max:a.at(-1)}}
(async()=>{const b=await chromium.launch({executablePath:process.env.QURAN_CHROME||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true}),results=[];
for(const width of widths)for(const tajweed of ['off','on']){const c=await b.newContext({viewport:{width,height:844},serviceWorkers:'block'}),p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error')errors.push(m.text())});await p.goto(url);await p.evaluate(tajweed=>{localStorage.setItem('uwa-quran-reader-v1',JSON.stringify({mode:'classic',script:'uthmani',last:{mode:'classic',surah:1,ayah:1,page:1},bookmarks:[]}));localStorage.setItem('uwa-quran-tajweed-v1',tajweed)},tajweed);await p.reload();await p.locator('[data-app-view="allday"]').click();await p.locator('#quran-tab-library').click();await p.locator('#quran-continue').click();const measurements=[];
for(let n=1;n<=604;n++){await ready(p,n);const seen=await measure(p),data=json(`quran/pages/${String(n).padStart(3,'0')}.json`),tokens=data.lines.flat(),annotations=json(`quran/tajweed/pages/${String(n).padStart(3,'0')}.json`),segments=new Map(annotations.tokens.map(([l,i,v])=>[`${l}:${i}`,v])),expected=[];if(tajweed==='on')for(const [l,line] of data.lines.entries())for(const [i,token] of line.entries())for(const [a,b,rule] of segments.get(`${l}:${i}`)||[])expected.push(['tajweed-'+classes[rule],Array.from(token[1]).slice(a,b).join('')]);const label=`${width}/${tajweed}/${n}`;
assert.deepEqual(seen.words,tokens.filter(x=>['word','bismillah'].includes(x[0])).map(x=>x[1]),label+' text');assert.deepEqual(seen.lines,data.lines.map(line=>line.map(([kind,t,key,s])=>kind==='surah_header'?'سُورَةُ '+chapters[s-1][2]:kind==='end'?arabic(key.split(':')[1]):kind==='quarter'?'۞':t)),label+' QCF identities/order');assert.deepEqual(seen.markers,tokens.filter(x=>x[0]==='end').map(x=>x[2]),label+' markers');assert.deepEqual(seen.colours.map(x=>x.slice(0,2)),expected,label+' annotations');for(const [cls,t,color,hex] of seen.colours)assert.equal(color,`rgb(${hex.match(/[a-f0-9]{2}/gi).map(x=>parseInt(x,16)).join(', ')})`,label+' palette');assert.equal(seen.quarters,tokens.filter(x=>x[0]==='quarter').length);assert.equal(seen.sajdah,tokens.filter(x=>x[0]==='sajdah').length);
assert(seen.font>=11&&seen.font<=28&&seen.font*4===Math.round(seen.font*4),label+' font range');assert(seen.contentHeight<=seen.innerHeight*.97+.01,label+' height reserve');assert(seen.horizontalOverflow<=0&&seen.verticalOverflow<=0&&seen.documentOverflow<=0&&seen.screenHeight<=seen.viewportHeight+1,label+' overflow '+JSON.stringify(seen));assert.deepEqual(seen.escapes,[],label+' ink/marker frame bounds');assert(seen.pairedMarkers,label+' markers paired with preceding words');
if(reps.includes(n)||seen.sparePercent>8)await assertLargest(p,seen.font);
if(reps.includes(n)){await p.locator('#quran-classic-page').screenshot({path:`${out}/classic-${n}-${width}-${tajweed}.png`})}else if(seen.sparePercent>8)await p.locator('#quran-classic-page').screenshot({path:`${out}/spare-${n}-${width}-${tajweed}.png`});
measurements.push({page:n,font:seen.font,containerHeight:seen.containerHeight,innerHeight:seen.innerHeight,contentHeight:seen.contentHeight,sparePercent:seen.sparePercent,horizontalOverflow:seen.horizontalOverflow,verticalOverflow:seen.verticalOverflow,inkMarkerEscapes:0});if(n%100===0)console.log('checked',label);if(n<604)await p.locator('#quran-next-classic-bottom').evaluate(e=>e.click())}
assert.deepEqual(errors,[]);const result={width,tajweed,pages:604,errors:0,textMismatch:0,markerMismatch:0,horizontalOverflow:0,verticalOverflow:0,inkMarkerEscapes:0,font:stats(measurements.map(x=>x.font)),sparePercent:stats(measurements.map(x=>x.sparePercent)),atMax:measurements.filter(x=>x.font===28).length,nearMinimum:measurements.filter(x=>x.font<=12).length,above8Percent:measurements.filter(x=>x.sparePercent>8).map(x=>x.page),measurements};results.push(result);fs.writeFileSync(`${out}/mobile-${width}-${tajweed}.json`,JSON.stringify(result,null,2));console.log('PASS',JSON.stringify({...result,measurements:undefined}));await c.close()}
await b.close();fs.writeFileSync(out+'/mobile-sweep.json',JSON.stringify(results,null,2))})().catch(e=>{console.error(e);process.exit(1)});
