const {chromium}=require('playwright'),assert=require('assert'),fs=require('fs'),path=require('path');
const url=process.env.QURAN_QA_URL||'http://127.0.0.1:8826/',out=process.env.QURAN_QA_OUTPUT||'/Users/halimi_hanim/Projects/Islamic-App-QA-V2.6.3-UI-Polish';fs.mkdirSync(out,{recursive:true});
(async()=>{const b=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true}),results=[];try{
for(const width of [320,390,1280]){
 const c=await b.newContext({viewport:{width,height:844},serviceWorkers:'block',timezoneId:'Asia/Kuala_Lumpur'}),p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error')errors.push(m.text())});await p.goto(url);await p.evaluate(()=>{localStorage.clear();localStorage.setItem('uwa-navigation-renovation-trial-v1-initialized','{"schema":1}');localStorage.setItem('uwa-navigation-renovation-trial-v1-members-allday','["4","15"]');localStorage.setItem('uwa-navigation-renovation-trial-v1-order-allday','["15","4"]');localStorage.setItem('uwa-quran-reader-v1',JSON.stringify({bookmarks:['28:3'],last:{surah:2,ayah:20,page:4,mode:'list'},script:'uthmani',mode:'list',uthmaniMode:'list'}))});await p.reload();await p.locator('[data-app-view="allday"]').click();await p.waitForFunction(()=>document.querySelector('[data-favourite="28:3"] .quran-verse-arabic'));await p.evaluate(()=>document.fonts.ready);
 const protectedState=await p.evaluate(()=>Object.fromEntries(Object.keys(localStorage).filter(k=>k.includes('migration-backup')||k.endsWith('-migrated')||k.startsWith('uwa-navigation-renovation')).map(k=>[k,localStorage.getItem(k)])));
 assert.equal(await p.locator('#quran-migration-notice').innerText(),'');assert.equal(await p.locator('#quran-migration-notice').evaluate(e=>e.getBoundingClientRect().height),0);assert(!await p.locator('#quran-routine').innerText().then(t=>t.includes('Sebahagian bacaan lama ialah petikan')));
 const geometry=await p.evaluate(()=>{const add=document.querySelector('#quran-add'),rows=[...document.querySelectorAll('#allday-checklist .check-row')],a=add.getBoundingClientRect(),last=rows.at(-1).getBoundingClientRect(),f=document.querySelector('#quran-favourites').getBoundingClientRect();return {label:add.textContent,width:a.width,rowWidth:last.width,height:a.height,rowHeight:last.height,afterLast:a.top>=last.bottom,beforeFavourites:a.bottom<=f.top,insideChecklist:!!add.closest('#allday-checklist'),surah:add.dataset.zikirId||add.dataset.surah,controls:add.querySelectorAll('input,.repeat-badge,.drag-handle').length,buttons:document.querySelectorAll('#quran-add').length,overflow:document.documentElement.scrollWidth>innerWidth,header:[...document.querySelector('.routine-head-actions').children].map(e=>e.textContent)}});
 assert.equal(geometry.label,'+ Tambah Surah');assert.equal(geometry.buttons,1);assert.equal(geometry.width,geometry.rowWidth);assert(Math.abs(geometry.height-geometry.rowHeight)<=3);assert(geometry.afterLast&&geometry.beforeFavourites);assert.equal(geometry.insideChecklist,false);assert.equal(geometry.surah,undefined);assert.equal(geometry.controls,0);assert.equal(geometry.overflow,false);await p.screenshot({path:out+`/polish-populated-${width}.png`,fullPage:true});await p.locator('#quran-add').evaluate(e=>scrollTo({top:scrollY+e.getBoundingClientRect().top-180,behavior:'instant'}));await p.screenshot({path:out+`/polish-add-${width}.png`,fullPage:false});
 const savedHistory=await p.evaluate(()=>localStorage.getItem('uwa-quran-recent-v1'));await p.locator('#quran-add').click();await p.locator('#quran-search').fill('Fatihah');await p.locator('[data-surah="1"]').click();await p.locator('#quran-search').fill('2');await p.locator('[data-surah="2"]').click();await p.locator('#quran-selection-done').click();assert.equal(await p.locator('#allday-checklist .check-row').count(),5);assert.equal(await p.locator('#allday-count-big').innerText(),'0/5');assert.equal(await p.evaluate(()=>document.activeElement.id),'quran-add');assert.equal(await p.locator('#allday-sort-status').innerText(),'Surah ditambah.');assert.equal(await p.evaluate(()=>localStorage.getItem('uwa-quran-recent-v1')),savedHistory);
 await p.locator('#quran-add').click();await p.locator('[data-surah="3"]').click();await p.locator('#quran-selection-cancel').click();assert.equal(await p.evaluate(()=>document.activeElement.id),'quran-add');assert.equal(await p.locator('#allday-checklist .check-row').count(),5);await p.locator('#quran-add').click();await p.locator('[data-surah="3"]').click();await p.goBack();await p.locator('#quran-routine').waitFor({state:'visible'});assert.equal(await p.evaluate(()=>document.activeElement.id),'quran-add');
 await p.locator('[data-sort="allday"]').click();assert.equal(await p.locator('#quran-add .drag-handle').count(),0);const handle=p.locator('#allday-checklist [data-zikir-id="112"] .drag-handle');await handle.focus();await p.keyboard.press('Space');await p.keyboard.press('ArrowDown');await p.keyboard.press('Enter');await handle.focus();await p.keyboard.press('Space');await p.keyboard.press('Delete');assert.equal(await p.locator('#allday-checklist .check-row').count(),4);assert.equal(await p.locator('#quran-add').count(),1);await p.locator('[data-undo="allday"]').click();assert.equal(await p.locator('#allday-checklist .check-row').count(),5);await p.locator('[data-sort="allday"]').click();
 // Existing favourites save/open and recent resume remain functional.
 await p.locator('[data-favourite-open="28:3"]').click();await p.waitForFunction(()=>document.querySelector('#quran-ayah-3')?.getBoundingClientRect().top>=70&&document.querySelector('#quran-ayah-3')?.getBoundingClientRect().top<130);assert.equal(await p.locator('[data-bookmark="28:3"]').getAttribute('aria-pressed'),'true');await p.locator('[data-bookmark="28:4"]').click();assert.equal(await p.locator('[data-bookmark="28:4"]').getAttribute('aria-pressed'),'true');await p.locator('#quran-back').click();await p.waitForFunction(()=>document.activeElement?.dataset.favouriteOpen==='28:3');assert.equal(await p.locator('[data-favourite="28:4"]').count(),1);await p.locator('[data-favourite-remove="28:4"]').click();await p.locator('#quran-tab-library').click();await p.locator('[data-recent-surah="28"]').click();await p.waitForFunction(()=>document.querySelector('#quran-ayah-3')?.getBoundingClientRect().top>=70&&document.querySelector('#quran-ayah-3')?.getBoundingClientRect().top<130);await p.locator('#quran-back').click();await p.locator('#quran-tab-routine').click();
 // Frozen virtual clock gives exact deadlines, using the production add handler.
 await p.clock.install({time:new Date('2026-10-04T04:00:00Z')});await p.clock.pauseAt(new Date('2026-10-04T04:01:00Z'));assert(await p.evaluate(()=>QuranRoutine.add(['3'])));await p.clock.fastForward(14000);assert.equal(await p.locator('#allday-sort-status').textContent(),'Surah ditambah.');await p.evaluate(()=>window.dispatchEvent(new CustomEvent('quran-catalogue',{detail:[]})));await p.clock.fastForward(999);assert.equal(await p.locator('#allday-sort-status').textContent(),'Surah ditambah.');await p.clock.fastForward(1);assert.equal(await p.locator('#allday-sort-status').textContent(),'');assert.equal(await p.locator('#allday-sort-status').evaluate(e=>e.getBoundingClientRect().height),0);assert.equal(await p.locator('#allday-sort-status').evaluate(e=>e.parentElement.getBoundingClientRect().height),0);
 assert(await p.evaluate(()=>QuranRoutine.add(['5'])));await p.clock.fastForward(10000);assert(await p.evaluate(()=>QuranRoutine.add(['6'])));await p.clock.fastForward(5000);assert.equal(await p.locator('#allday-sort-status').textContent(),'Surah ditambah.');await p.clock.fastForward(9999);assert.equal(await p.locator('#allday-sort-status').textContent(),'Surah ditambah.');await p.clock.fastForward(1);assert.equal(await p.locator('#allday-sort-status').textContent(),'');
 assert(await p.evaluate(()=>QuranRoutine.add(['7'])));await p.clock.fastForward(1000);await p.evaluate(()=>{window.qaSet=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k.startsWith('uwa-quran-checklist-v1-daily-'))throw Error('synthetic refusal');return window.qaSet.call(this,k,v)};const checkbox=document.querySelector('#allday-checklist input');checkbox.checked=true;checkbox.dispatchEvent(new Event('change',{bubbles:true}))});const warning=await p.locator('#allday-sort-status').textContent();assert.match(warning,/tidak dapat disimpan/);await p.clock.fastForward(20000);assert.equal(await p.locator('#allday-sort-status').textContent(),warning);await p.evaluate(()=>Storage.prototype.setItem=window.qaSet);
 // Text guard also rejects an obsolete callback if another code path replaces the notice.
 assert(await p.evaluate(()=>QuranRoutine.add(['8'])));await p.evaluate(()=>document.querySelector('#allday-sort-status').textContent='Synthetic newer message');await p.clock.fastForward(15000);assert.equal(await p.locator('#allday-sort-status').textContent(),'Synthetic newer message');await p.clock.resume();await p.reload();await p.locator('[data-app-view="allday"]').click();assert.equal(await p.locator('#allday-sort-status').textContent(),'');
 assert.deepEqual(await p.evaluate(()=>Object.fromEntries(Object.keys(localStorage).filter(k=>k.includes('migration-backup')||k.endsWith('-migrated')||k.startsWith('uwa-navigation-renovation')).map(k=>[k,localStorage.getItem(k)]))),protectedState);
 await p.evaluate(()=>{localStorage.setItem('uwa-quran-checklist-v1-members','[]');localStorage.setItem('uwa-quran-checklist-v1-order','[]')});await p.reload();await p.locator('[data-app-view="allday"]').click();await p.locator('#quran-empty').waitFor({state:'visible'});assert.equal(await p.locator('#allday-count-big').innerText(),'0/0');assert.equal(await p.locator('#allday-checklist .check-row').count(),0);assert.equal(await p.locator('#quran-add').count(),1);assert(await p.evaluate(()=>document.querySelector('#quran-add').getBoundingClientRect().top>=document.querySelector('#quran-empty').getBoundingClientRect().bottom));await p.screenshot({path:out+`/polish-empty-${width}.png`,fullPage:true});assert.deepEqual(errors,[]);results.push({width,geometry,addSearchMultiSelectCancelBackFocus:true,sortRemoveUndoExcluded:true,favouritesRecentSmoke:true,expiresExactly15000:true,rerenderDoesNotExtend:true,successResetsDeadline:true,oldTimerCannotEraseErrorOrMessage:true,reloadNotPersisted:true,migrationNoticeAbsentDataUnchanged:true,emptyPlacement:true,errors:0});await c.close();console.log('passed width',width);
}
// Actionable initialization/storage warning remains visible.
const c=await b.newContext({serviceWorkers:'block'}),p=await c.newPage();await p.goto(url);await p.evaluate(()=>localStorage.setItem('uwa-quran-checklist-v1-migrated','broken'));await p.reload();await p.locator('[data-app-view="allday"]').click();assert.match(await p.locator('#quran-migration-notice').innerText(),/belum dapat disediakan/);assert.equal(await p.locator('#quran-add').isDisabled(),true);await c.close();fs.writeFileSync(out+'/ui-polish.json',JSON.stringify({url,widths:results,initializationWarningPreserved:true,physicalIPhoneTested:false},null,2));console.log('PASS UI Polish');
}finally{await b.close()}})().catch(e=>{console.error(e);process.exit(1)});
