const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const root=path.resolve(__dirname,'..'),out=process.env.QURAN_QA_OUTPUT||'/Users/halimi_hanim/Projects/Islamic-App-QA-V2.6.4',baseline=process.env.QURAN_QA_BASELINE||'/private/tmp/quran-v264-baseline',cache='uwa-bacaan-harian-v264-custom-delete-fix';let served=baseline;
const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.ttf':'font/ttf','.webmanifest':'application/manifest+json','.png':'image/png'};
const server=http.createServer((req,res)=>{const pn=decodeURIComponent(new URL(req.url,'http://localhost').pathname),file=path.join(served,pn==='/'?'index.html':pn);if(!file.startsWith(served+path.sep)){res.writeHead(403).end();return}try{res.writeHead(200,{'Content-Type':mime[path.extname(file)]||'application/octet-stream','Cache-Control':'no-store'});res.end(fs.readFileSync(file))}catch{res.writeHead(404).end()}});
const snapshot=p=>p.evaluate(()=>Object.fromEntries(Object.keys(localStorage).map(k=>[k,localStorage.getItem(k)])));
(async()=>{fs.mkdirSync(out,{recursive:true});await new Promise(r=>server.listen(8828,'127.0.0.1',r));const url=process.env.QURAN_QA_URL||'http://127.0.0.1:8828/',b=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});try{
 const c=await b.newContext({viewport:{width:390,height:844},timezoneId:'Asia/Kuala_Lumpur'}),p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(url);await p.evaluate(()=>navigator.serviceWorker.ready);await p.waitForFunction(()=>navigator.serviceWorker.controller);
 if(!process.env.QURAN_QA_URL)assert.deepEqual(await p.evaluate(()=>caches.keys()),['uwa-bacaan-harian-v263-ui-polish-1']);
 await p.evaluate(()=>{localStorage.clear();const data={'uwa-theme':'emerald','uwa-custom-readings-v1':JSON.stringify([{id:'u-legacy',name:'Synthetic legacy Quran excerpt',arabic:'نص',meaning:'synthetic',reference:''},{id:'u-other',name:'Synthetic retained entry',arabic:'',meaning:'',reference:''}]),'uwa-deleted-reading-ids-v1':'["u-old"]','uwa-navigation-renovation-trial-v1-initialized':'{"schema":1}','uwa-navigation-renovation-trial-v1-members-allday':'["u-legacy","4"]','uwa-navigation-renovation-trial-v1-order-allday':'["u-legacy","4"]','uwa-navigation-renovation-trial-v1-daily-2026-10-04-allday':'["u-legacy"]','uwa-quran-checklist-v1-members':'["112","114"]','uwa-quran-checklist-v1-order':'["114","112"]','uwa-quran-checklist-v1-daily-2026-10-04':'["112"]','uwa-quran-checklist-v1-migrated':'{"schema":1,"unmapped":["u-legacy"]}','uwa-quran-checklist-v1-migration-backup':'{"members":["u-legacy","4"]}','uwa-quran-reader-v1':JSON.stringify({bookmarks:['2:20'],script:'uthmani',mode:'list',uthmaniMode:'list',last:{surah:2,ayah:20,page:4,mode:'list'}}),'uwa-quran-reader-v1-bookmarks-backup-v263':'{"schema":1,"bookmarks":["2:20"]}','uwa-quran-recent-v1':'{"schema":1,"entries":[{"surah":2,"ayah":20,"mode":"list"}]}','uwa-quran-recent-v1-legacy-backup':'{"last":{"surah":2,"ayah":20}}','uwa-quran-tajweed-v1':'on','uwa-selawat-21-stanzas-v1':'["1"]'};for(const t of ['morning','evening']){data['uwa-navigation-renovation-trial-v1-members-'+t]='["1","u-legacy","u-other"]';data['uwa-navigation-renovation-trial-v1-order-'+t]='["u-other","1","u-legacy"]';data['uwa-navigation-renovation-trial-v1-daily-2026-10-04-'+t]='["u-legacy","u-other"]'}for(const[k,v]of Object.entries(data))localStorage.setItem(k,v)});
 const before=await snapshot(p);
 if(!process.env.QURAN_QA_URL){served=root;await p.evaluate(async()=>{await(await navigator.serviceWorker.getRegistration()).update()});}
 await p.waitForFunction(async cache=>{const keys=await caches.keys();return keys.length===1&&keys[0]===cache},cache);
 await p.reload();assert.deepEqual(await snapshot(p),before);assert.equal(await p.evaluate(()=>typeof window.planCustomSourceDeletion),'function');
 const assets=['index.html','source-delete.js?v=264','quran/reader.js?v=264','quran/reader.css?v=264','quran/favourites.js?v=264','quran/recent.js?v=264','quran/checklist.js?v=264'];for(const a of assets){const text=await p.evaluate(async({cache,a})=>{const r=await(await caches.open(cache)).match('./'+a);return r?await r.text():null},{cache,a});assert.equal(text,fs.readFileSync(path.join(root,a.split('?')[0]),'utf8'),a)}
 await p.locator('[data-app-view="allday"]').click();await p.waitForFunction(()=>document.querySelector('[data-favourite="2:20"] .quran-verse-arabic'));await p.locator('[data-favourite-open="2:20"]').click();await p.waitForFunction(()=>document.querySelector('#quran-ayah-20'));await p.locator('#quran-back').click();const warmed=await snapshot(p);
 await c.setOffline(true);await p.reload();await p.locator('[data-app-view="reference"]').click();await p.locator('tr[data-reading-id="u-legacy"] .toc-row-actions button').last().click();await p.locator('#delete-reading').click();await p.locator('#delete-accept').click();assert.equal(await p.locator('#app-feedback').textContent(),'Bacaan dipadam.');
 const after=await snapshot(p);for(const[k,v]of Object.entries(warmed)){if(k.startsWith('uwa-quran-')||k.includes('allday')||k.includes('backup')||k.includes('selawat'))assert.equal(after[k],v,k)}assert.deepEqual(JSON.parse(after['uwa-custom-readings-v1']).map(i=>i.id),['u-other']);for(const t of ['morning','evening'])for(const kind of ['members','order','daily-2026-10-04'])assert(!JSON.parse(after['uwa-navigation-renovation-trial-v1-'+kind+'-'+t]).includes('u-legacy'));
 await p.reload();assert.equal(await p.locator('tr[data-reading-id="u-legacy"]').count(),0);await p.locator('[data-app-view="allday"]').click();await p.waitForFunction(()=>document.querySelector('[data-favourite="2:20"] .quran-verse-arabic'));await p.locator('[data-favourite-open="2:20"]').click();await p.waitForFunction(()=>{const r=document.querySelector('#quran-ayah-20')?.getBoundingClientRect();return r&&r.top>=70&&r.top<130});await p.locator('#quran-back').click();await p.locator('#quran-favourites').scrollIntoViewIfNeeded();await p.screenshot({path:path.join(out,'delete-offline-quran-390.png')});assert.deepEqual(errors,[]);
 const result={url,upgradeFromBaseline:!process.env.QURAN_QA_URL,allStorageRawBytesPreservedOnUpgrade:true,cacheKeys:await p.evaluate(()=>caches.keys()),cachedAssetsMatch:assets,offlineCustomDeleteAndReload:true,quranAndRecoveryStateUnchangedByDelete:true,offlineFavouriteExactAyah:true,errors};fs.writeFileSync(path.join(out,'custom-delete-pwa.json'),JSON.stringify(result,null,2));console.log('PASS',JSON.stringify(result));
}finally{await b.close();server.close()}})().catch(e=>{console.error(e);server.close();process.exit(1)});
