// V2.5.2 desktop Classic and unchanged modern Page against a served V2.5.1 baseline.
// Set QURAN_QA_BASELINE to the unmodified V2.5.1 server. Playwright via NODE_PATH.
const {PNG}=require('pngjs');
const {chromium}=require('playwright'),fs=require('fs'),assert=require('assert');
const url=process.env.QURAN_QA_URL||'http://127.0.0.1:8821/',baseline=process.env.QURAN_QA_BASELINE||'http://127.0.0.1:8822/',out=process.env.QURAN_QA_OUTPUT||'/private/tmp/quran-desktop-qa';fs.mkdirSync(out,{recursive:true});
const reps=(process.env.QURAN_QA_PAGES||'1,7,12,303,420,534,535,597,604').split(',').map(Number),widths=(process.env.QURAN_QA_WIDTHS||'320,390,1024,1280,1440').split(',').map(Number),result=[];
async function open(p,url,mode,n){await p.goto(url);await p.evaluate(({mode,n})=>{localStorage.setItem('uwa-quran-reader-v1',JSON.stringify({mode,script:'uthmani',last:{mode,surah:1,ayah:1,page:n},bookmarks:[]}));localStorage.setItem('uwa-quran-tajweed-v1','on')},{mode,n});await p.reload();await p.locator('[data-app-view="allday"]').click();await p.locator('#quran-tab-library').click();await p.locator('#quran-continue').click();await ready(p,mode,n);await p.evaluate(()=>document.fonts.ready);await p.waitForTimeout(60)}
async function ready(p,mode,n){await p.waitForFunction(({mode,n})=>{const s=document.querySelector(mode==='classic'?'#quran-classic-page':'#quran-mushaf-page');return document.querySelector('#quran-reader-status').textContent===''&&s.querySelector('.quran-page-folio')?.textContent===String(n).replace(/\d/g,d=>'٠١٢٣٤٥٦٧٨٩'[+d])&&(mode!=='classic'||[...s.querySelectorAll('.quran-classic-line')].every(e=>e.style.fontSize))},{mode,n})}
async function measure(p,selector){return p.locator(selector).evaluate(s=>{const clone=s.cloneNode(true);clone.querySelectorAll('.quran-classic-section,.quran-classic-end-pair').forEach(e=>e.replaceWith(...e.childNodes));const sr=s.getBoundingClientRect(),rect=e=>{const r=e.getBoundingClientRect();return [r.x-sr.x,r.y-sr.y,r.width,r.height].map(x=>Math.round(x*100)/100)};return{text:s.textContent,html:clone.innerHTML,rect:rect(s),geometry:[...s.querySelectorAll('*')].filter(e=>!e.matches('.quran-classic-section,.quran-classic-end-pair')).map(e=>[e.className,rect(e),getComputedStyle(e).fontSize,getComputedStyle(e).color]),spans:[...s.querySelectorAll('[class^="tajweed-"]')].map(e=>[e.className,e.textContent,getComputedStyle(e).color,getComputedStyle(e).getPropertyValue('--'+e.className).trim()]),flow:[...s.querySelectorAll('.quran-page-flow')].map(e=>getComputedStyle(e).fontSize),lines:[...s.querySelectorAll('.quran-classic-line')].map(e=>({justify:getComputedStyle(e).justifyContent,gap:getComputedStyle(e).gap,font:getComputedStyle(e).fontSize,overflow:e.scrollWidth-e.clientWidth,children:[...e.children].flatMap(x=>x.classList.contains('quran-classic-end-pair')?[...x.children]:[x]).map(x=>rect(x))})),overflow:s.scrollWidth-s.clientWidth,doc:document.documentElement.scrollWidth-innerWidth}})}
function palette(r){for(const [cls,t,color,hex] of r.spans){assert(hex,'palette variable '+cls);assert.equal(color,`rgb(${hex.match(/[a-f0-9]{2}/gi).map(x=>parseInt(x,16)).join(', ')})`,'visible palette '+cls)}assert(r.spans.length>0)}
(async()=>{const b=await chromium.launch({executablePath:process.env.QURAN_CHROME||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});
for(const width of widths)for(const mode of ['classic','page']){if(mode==='classic'&&width<=620)continue;if(mode==='page'&&![320,390,1280].includes(width))continue;const contexts=await Promise.all([b.newContext({viewport:{width,height:1000},serviceWorkers:'block'}),b.newContext({viewport:{width,height:1000},serviceWorkers:'block'})]);const pages=await Promise.all(contexts.map(c=>c.newPage())),errors=[];for(const p of pages){p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error')errors.push(m.text())})}for(const n of reps){const selector=mode==='classic'?'#quran-classic-page':'#quran-mushaf-page';await Promise.all([open(pages[0],baseline,mode,n),open(pages[1],url,mode,n)]);const [before,after]=await Promise.all(pages.map(p=>measure(p,selector)));assert.equal(after.text,before.text);assert.equal(after.html,before.html);palette(after);assert(after.overflow<=1&&after.doc<=1&&after.lines.every(l=>l.overflow<=1));assert.deepEqual(after,before,'unchanged geometry '+mode+'/'+width+'/'+n);if(mode==='classic'&&width>620)assert(after.lines.every(l=>l.justify==='center'));if(mode==='page')assert(after.flow.every(x=>x==='32px'));const images=await Promise.all(pages.map((p,i)=>p.locator(selector).screenshot({path:`${out}/${i?'after':'before'}-${mode}-${n}-${width}.png`})));{const a=PNG.sync.read(images[0]),b=PNG.sync.read(images[1]);assert.equal(a.width,b.width);assert.equal(a.height,b.height);let borderPixelDifferences=0;for(let y=0;y<a.height;y++)for(let x=0;x<a.width;x++){const i=(y*a.width+x)*4;if(!a.data.subarray(i,i+4).equals(b.data.subarray(i,i+4))){assert(x<7||x>=a.width-7||y<7||y>=a.height-7,'reading pixels identical '+mode+'/'+width+'/'+n);borderPixelDifferences++}}assert(borderPixelDifferences<=32,'limited frame rasterization noise');}await pages[1].locator('#quran-settings-toggle').click();await pages[1].locator('#quran-tajweed-off').click();await ready(pages[1],mode,n);assert.equal(await pages[1].locator(selector+' [class^="tajweed-"]').count(),0);await pages[1].locator('#quran-tajweed-on').click();await ready(pages[1],mode,n);palette(await measure(pages[1],selector));result.push({width,mode,page:n,textPreserved:true,palette:true,offOn:true,noOverflow:true,readingPixelsIdentical:width<=620||mode==='page',beforeLines:before.lines,afterLines:after.lines});console.log('checked',width,mode,n)}assert.deepEqual(errors,[]);await Promise.all(contexts.map(c=>c.close()))}
for(const width of widths.filter(w=>w>620))for(const mode of ['classic','page']){const c=await b.newContext({viewport:{width,height:1000},serviceWorkers:'block',forcedColors:'active'}),p=await c.newPage();await open(p,url,mode,535);const selector=mode==='classic'?'#quran-classic-page':'#quran-mushaf-page',r=await measure(p,selector);if(width>620)palette(r);else assert(r.spans.every(s=>s[2]==='rgb(0, 0, 0)'),'phone forced-colours unchanged');await p.locator(selector).screenshot({path:`${out}/forced-colors-${mode}-535-${width}.png`});await p.locator('#quran-settings-toggle').click();await p.locator('#quran-tajweed-off').click();await ready(p,mode,535);assert.equal(await p.locator(selector+' [class^="tajweed-"]').count(),0);result.push({width,mode,forcedColors:true,desktopPalette:width>620,mobileUnchanged:width<=620,off:true});await c.close()}
await b.close();fs.writeFileSync(out+'/desktop-regression.json',JSON.stringify(result,null,2));console.log('PASS',result.length,'comparisons/forced-colour cases')})().catch(e=>{console.error(e);process.exit(1)});
