const fs=require('fs'),vm=require('vm'),assert=require('assert');
const chapters=JSON.parse(fs.readFileSync('quran/chapters.json')),scope={window:{}};vm.runInNewContext(fs.readFileSync('quran/favourites.js','utf8'),scope);
const key='uwa-quran-reader-v1',backup=key+'-bookmarks-backup-v263';let count=0;
function test(name,fn){fn();count++;console.log('PASS',name)}
function setup(bookmarks,extra={}){const data=new Map([[key,JSON.stringify({last:{surah:2,ayah:20,mode:'list',page:4},script:'simple',mode:'page',uthmaniMode:'classic',bookmarks,...extra})],['uwa-quran-recent-v1','unchanged'],['uwa-quran-checklist-v1-members','unchanged']]);const storage={getItem:k=>data.get(k)??null,setItem:(k,v)=>data.set(k,v),removeItem:k=>data.delete(k)};const model=scope.window.createQuranFavourites(chapters,storage);return {model,storage,data}}
const arr=v=>JSON.parse(JSON.stringify(v));
test('legacy reverse append order without writes',()=>{const{model,data}=setup(['1:1','2:286','114:6']);assert.deepEqual(arr(model.entries),['114:6','2:286','1:1']);assert(!data.has(backup))});
test('newest/dedup/remove/resave',()=>{const{model}=setup(['1:1']);assert(model.set('2:20',true));assert(model.set('2:20',true));assert.deepEqual(arr(model.entries),['2:20','1:1']);assert(model.set('1:1',false));assert(model.set('1:1',true));assert.deepEqual(arr(model.entries),['1:1','2:20'])});
test('bounds validate first/last and reject invalid',()=>{const{model}=setup([]);for(const k of ['1:1','2:286','114:6'])assert.equal(model.canonical(k),k);for(const k of ['0:1','115:1','1:0','1:8','2:287','114:7',null,{},'1:1x','-1:1'])assert.equal(model.canonical(k),null)});
test('mixed legacy reads retain raw and valid records',()=>{const raw=['1:1','x','0:1','01:001','114:6','114:7','2:286'];const{model,data}=setup(raw);assert.deepEqual(arr(model.entries),['2:286','114:6','1:1']);assert.deepEqual(JSON.parse(data.get(key)).bookmarks,raw);assert(!data.has(backup))});
test('cleanup backs up exact evidence before mutation, idempotent',()=>{const raw=['1:1','bad','01:001'];const{model,data}=setup(raw);assert(model.set('114:6',true));const first=data.get(backup);assert.deepEqual(JSON.parse(first),{schema:1,bookmarks:raw});assert.deepEqual(JSON.parse(data.get(key)).bookmarks,['1:1','114:6']);assert(model.set('2:1',true));assert.equal(data.get(backup),first)});
test('unrelated fields and storage preserved',()=>{const{model,data}=setup(['1:1'],{unknown:{keep:true}});const before=JSON.parse(data.get(key));assert(model.set('2:1',true));const after=JSON.parse(data.get(key));delete before.bookmarks;delete after.bookmarks;assert.deepEqual(after,before);assert.equal(data.get('uwa-quran-recent-v1'),'unchanged');assert.equal(data.get('uwa-quran-checklist-v1-members'),'unchanged')});
test('ordinary reader saves retain malformed bookmark evidence',()=>{const{model,data}=setup(['1:1','bad']);assert(model.saveReader({last:{surah:3,ayah:1},bookmarks:['wrong'],script:'uthmani',mode:'list',uthmaniMode:'list'}));assert.deepEqual(JSON.parse(data.get(key)).bookmarks,['1:1','bad']);assert(!data.has(backup))});
test('fresh persisted collection wins over stale reader state',()=>{const{model,data}=setup(['1:1']);let d=JSON.parse(data.get(key));d.bookmarks.push('114:6');data.set(key,JSON.stringify(d));assert(model.saveReader({last:null,bookmarks:['1:1'],mode:'list'}));assert.deepEqual(JSON.parse(data.get(key)).bookmarks,['1:1','114:6']);model.refresh();assert.deepEqual(arr(model.entries),['114:6','1:1'])});
test('read/reload and no daily reset',()=>{const{model,storage}=setup(['1:1']);model.set('114:6',true);const next=scope.window.createQuranFavourites(chapters,storage);assert.deepEqual(arr(next.entries),['114:6','1:1'])});
test('no collection cap',()=>{const{model}=setup([]);for(let a=1;a<=286;a++)assert(model.set(`2:${a}`,true));assert.equal(model.entries.length,286)});
test('write refusal no false membership, retry',()=>{const{model,storage,data}=setup(['1:1']);const raw=data.get(key),set=storage.setItem;storage.setItem=()=>{throw Error()};assert.equal(model.set('2:1',true),false);assert.deepEqual(arr(model.entries),['1:1']);assert.equal(data.get(key),raw);assert(model.error);storage.setItem=set;assert(model.set('2:1',true));assert.deepEqual(arr(model.entries),['2:1','1:1'])});
test('remove refusal retains saved state',()=>{const{model,storage}=setup(['1:1']);storage.setItem=()=>{throw Error()};assert.equal(model.set('1:1',false),false);assert.deepEqual(arr(model.entries),['1:1'])});
test('silent refusal detected',()=>{const{model,storage}=setup(['1:1']);storage.setItem=()=>{};assert.equal(model.set('2:1',true),false);assert.deepEqual(arr(model.entries),['1:1'])});
test('backup refusal blocks cleanup',()=>{const{model,storage,data}=setup(['1:1','bad']);const raw=data.get(key),set=storage.setItem;storage.setItem=(k,v)=>{if(k===backup)throw Error();set(k,v)};assert.equal(model.set('2:1',true),false);assert.equal(data.get(key),raw)});
test('invalid JSON/root preserved without cleanup',()=>{for(const raw of ['{','null','[]','42']){const{model,data}=setup([]);data.set(key,raw);assert.equal(model.refresh(),false);assert.equal(model.set('1:1',true),false);assert.equal(model.saveReader({mode:'list'}),false);assert.equal(data.get(key),raw)}});
test('storage read refusal blocks saves',()=>{const{model,storage}=setup(['1:1']);storage.getItem=()=>{throw Error()};assert.equal(model.refresh(),false);assert.equal(model.set('2:1',true),false)});
test('non-array bookmarks preserved until explicit mutation',()=>{const{model,data}=setup({bad:true});assert.deepEqual(arr(model.entries),[]);assert(model.set('1:1',true));assert.deepEqual(JSON.parse(data.get(backup)).bookmarks,{bad:true});assert.deepEqual(JSON.parse(data.get(key)).bookmarks,['1:1'])});
test('readback failure restores original before read recovers',()=>{const{model,storage,data}=setup(['1:1']);const raw=data.get(key),get=storage.getItem,set=storage.setItem;let refuse=false;storage.setItem=(k,v)=>{set(k,v);if(k===key&&v!==raw)refuse=true};storage.getItem=k=>{if(k===key&&refuse){refuse=false;throw Error()}return get(k)};assert.equal(model.set('2:1',true),false);assert.equal(data.get(key),raw);assert.deepEqual(arr(model.entries),['1:1'])});
test('unverifiable rollback reports recovery uncertainty',()=>{const{model,storage,data}=setup(['1:1']);const raw=data.get(key),set=storage.setItem;storage.setItem=(k,v)=>{if(k===key&&v===raw)throw Error();set(k,v)};let reads=0;const get=storage.getItem;storage.getItem=k=>{if(k===key&&++reads>1)return 'different';return get(k)};assert.equal(model.set('2:1',true),false);assert.match(model.error,/pemulihan belum/);assert.deepEqual(arr(model.entries),['1:1'])});
console.log('PASS',count,'favourites model cases');
