const {chromium}=require('playwright'),assert=require('assert'),fs=require('fs'),path=require('path'),http=require('http');
const root=path.resolve(__dirname,'..'),baseline=process.env.QURAN_QA_BASELINE||'/Users/halimi_hanim/.codex/worktrees/v251-desktop-fix/Islamic App',out=process.env.QURAN_QA_OUTPUT||'/Users/halimi_hanim/Projects/Islamic-App-QA-V2.6.1';
let served=baseline;const mime={'.html':'text/html','.js':'text/javascript','.json':'application/json','.css':'text/css','.ttf':'font/ttf','.png':'image/png','.webmanifest':'application/manifest+json'};
const server=http.createServer((req,res)=>{const pathname=decodeURIComponent(new URL(req.url,'http://localhost').pathname),file=path.join(served,pathname==='/'?'index.html':pathname);if(!file.startsWith(served+path.sep)){res.writeHead(403).end();return}try{const bytes=fs.readFileSync(file);res.writeHead(200,{'Content-Type':mime[path.extname(file)]||'application/octet-stream','Cache-Control':'no-store'});res.end(bytes)}catch{res.writeHead(404).end()}});
(async()=>{
 await new Promise(r=>server.listen(8828,'127.0.0.1',r));const url=process.env.QURAN_QA_URL||'http://127.0.0.1:8828/';
 const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true}),ctx=await browser.newContext({viewport:{width:390,height:844},timezoneId:'Asia/Kuala_Lumpur'}),p=await ctx.newPage(),errors=[];
 p.on('pageerror',e=>errors.push(e.message));
 await p.goto(url);await p.evaluate(()=>navigator.serviceWorker.ready);await p.waitForFunction(()=>navigator.serviceWorker.controller);
 if(!process.env.QURAN_QA_URL){
  assert.deepEqual(await p.evaluate(()=>caches.keys()),['uwa-bacaan-harian-v252-classic-mobile']);
  await p.evaluate(()=>{const pre='uwa-navigation-renovation-trial-v1',now=new Date(),day=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')}`;localStorage.setItem(pre+'-members-allday','["4","15","17"]');localStorage.setItem(pre+'-order-allday','["17","4","15"]');localStorage.setItem(pre+'-daily-'+day+'-allday','["4"]');localStorage.setItem('uwa-quran-reader-v1',JSON.stringify({mode:'list',script:'uthmani',bookmarks:['1:2']}));localStorage.setItem('uwa-quran-tajweed-v1','on')});
  served=root;await p.evaluate(async()=>{const registration=await navigator.serviceWorker.getRegistration();await registration.update()});
  await p.waitForFunction(async()=>{const keys=await caches.keys();return keys.length===1&&keys[0]==='uwa-bacaan-harian-v261-independent-quran'});await p.reload();
  await p.locator('[data-app-view="allday"]').click();assert.equal(await p.locator('#allday-count-big').textContent(),'3/3');assert.equal(await p.evaluate(()=>JSON.parse(localStorage.getItem('uwa-quran-reader-v1')).bookmarks[0]),'1:2');
 }
 await p.waitForFunction(()=>window.QuranChecklist?.ready);await p.locator('[data-app-view="allday"]').click();
 await p.locator('#quran-add').click();await p.locator('[data-surah="1"]').click();await p.locator('#quran-selection-done').click();
 await p.locator('#allday-checklist [data-zikir-id="1"] input').check();await p.locator('#allday-checklist [data-zikir-id="1"] .checklist-name').click();await p.waitForFunction(()=>document.querySelectorAll('#quran-verse-list .quran-verse').length===7);
 await p.locator('#quran-settings-toggle').click();await p.locator('#quran-page-mode').click();await p.waitForFunction(()=>document.querySelector('#quran-mushaf-page .quran-page-folio')&&document.querySelector('#quran-reader-status').textContent==='');
 await p.locator('#quran-tajweed-on').click();await p.locator('#quran-classic-mode').click();await p.waitForFunction(()=>document.querySelector('#quran-classic-page .quran-page-folio')&&document.querySelector('#quran-reader-status').textContent==='');
 await p.locator('#quran-script-simple').click();await p.waitForFunction(()=>document.querySelector('#quran-mushaf-page .quran-simple-verse')&&document.querySelector('#quran-reader-status').textContent==='');await p.locator('#quran-list-mode').click();await p.waitForFunction(()=>document.querySelectorAll('#quran-verse-list .quran-verse').length===7);await p.locator('#quran-settings-close').click();
 // Ensure each required cached data request completed before disconnecting.
 await p.waitForFunction(async()=>{const cache=await caches.open('uwa-bacaan-harian-v261-independent-quran');return Boolean(await cache.match('./quran/scripts/simple/surah/001.json'))});
 const saved=await p.evaluate(()=>Object.fromEntries(Object.keys(localStorage).filter(k=>k.startsWith('uwa-quran-checklist-v1')).map(k=>[k,localStorage.getItem(k)])));
 await ctx.setOffline(true);await p.reload();await p.locator('[data-app-view="allday"]').click();assert(await p.locator('#allday-checklist [data-zikir-id="1"] input').isChecked());
 await p.locator('#quran-add').click();assert.equal(await p.locator('#quran-surah-list button').count(),114);await p.locator('#quran-selection-cancel').click();
 await p.locator('#allday-checklist [data-zikir-id="1"] .checklist-name').click();await p.waitForFunction(()=>document.querySelectorAll('#quran-verse-list .quran-verse').length===7);
 await p.locator('#quran-settings-toggle').click();await p.locator('#quran-page-mode').click();await p.waitForFunction(()=>document.querySelector('#quran-mushaf-page .quran-page-folio')&&document.querySelector('#quran-reader-status').textContent==='');await p.locator('#quran-script-uthmani').click();await p.waitForFunction(()=>document.querySelector('#quran-mushaf-page [class^="tajweed-"], #quran-classic-page [class^="tajweed-"]'));await p.locator('#quran-classic-mode').click();await p.waitForFunction(()=>document.querySelector('#quran-classic-page .quran-page-folio')&&document.querySelector('#quran-reader-status').textContent==='');await p.locator('#quran-settings-close').click();await p.screenshot({path:out+'/offline-classic.png',fullPage:true});
 assert.deepEqual(await p.evaluate(()=>Object.fromEntries(Object.keys(localStorage).filter(k=>k.startsWith('uwa-quran-checklist-v1')).map(k=>[k,localStorage.getItem(k)]))),saved);
 const newPage=await ctx.newPage();await newPage.goto(url);await newPage.locator('[data-app-view="allday"]').click();assert(await newPage.locator('#allday-checklist [data-zikir-id="1"] input').isChecked());await newPage.locator('#allday-checklist [data-zikir-id="1"] .checklist-name').click();await newPage.waitForFunction(()=>document.querySelector('#quran-classic-page .quran-page-folio')&&document.querySelector('#quran-reader-status').textContent==='');
 assert.deepEqual(errors,[]);const report={url,upgrade:!process.env.QURAN_QA_URL,cache:await p.evaluate(()=>caches.keys()),offlineChecklistCatalogue:true,offlineUthmaniSimpleListPageClassic:true,newOfflineTab:true,userStatePreserved:true,errors};fs.writeFileSync(out+(process.env.QURAN_QA_URL?'/production-pwa.json':'/pwa.json'),JSON.stringify(report,null,2));console.log('PASS',JSON.stringify(report));await browser.close();server.close();
})().catch(e=>{console.error(e);server.close();process.exit(1)});
