const {chromium}=require('playwright'),assert=require('assert'),fs=require('fs'),path=require('path'),http=require('http');
const root=path.resolve(__dirname,'..'),baseline=process.env.QURAN_QA_BASELINE||'/private/tmp/quran-v262-baseline',out=process.env.QURAN_QA_OUTPUT||'/Users/halimi_hanim/Projects/Islamic-App-QA-V2.6.2';fs.mkdirSync(out,{recursive:true});
let served=baseline;const mime={'.html':'text/html','.js':'text/javascript','.json':'application/json','.css':'text/css','.ttf':'font/ttf','.png':'image/png','.webmanifest':'application/manifest+json'};
const server=http.createServer((req,res)=>{const pathname=decodeURIComponent(new URL(req.url,'http://localhost').pathname),file=path.join(served,pathname==='/'?'index.html':pathname);if(!file.startsWith(served+path.sep)){res.writeHead(403).end();return}try{res.writeHead(200,{'Content-Type':mime[path.extname(file)]||'application/octet-stream','Cache-Control':'no-store'});res.end(fs.readFileSync(file))}catch{res.writeHead(404).end()}});
(async()=>{
 await new Promise(r=>server.listen(8828,'127.0.0.1',r));const url=process.env.QURAN_QA_URL||'http://127.0.0.1:8828/';
 const b=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true}),ctx=await b.newContext({viewport:{width:390,height:844},timezoneId:'Asia/Kuala_Lumpur'}),p=await ctx.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(url);await p.evaluate(()=>navigator.serviceWorker.ready);await p.waitForFunction(()=>navigator.serviceWorker.controller);
 if(!process.env.QURAN_QA_URL)assert.deepEqual(await p.evaluate(()=>caches.keys()),['uwa-bacaan-harian-v261-independent-quran']);
 const oldState=await p.evaluate(()=>{const prefix='uwa-quran-checklist-v1',now=new Date(),day=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')}`;localStorage.setItem(prefix+'-members','["112","114"]');localStorage.setItem(prefix+'-order','["114","112"]');localStorage.setItem(prefix+'-daily-'+day,'["112"]');localStorage.setItem('uwa-quran-reader-v1',JSON.stringify({last:{surah:2,ayah:20,page:4,mode:'list'},mode:'list',script:'simple',uthmaniMode:'classic',bookmarks:['2:20']}));localStorage.setItem('uwa-quran-tajweed-v1','on');localStorage.removeItem('uwa-quran-recent-v1');localStorage.removeItem('uwa-quran-recent-v1-legacy-backup');return Object.fromEntries(Object.keys(localStorage).filter(k=>k.startsWith(prefix)).map(k=>[k,localStorage.getItem(k)]))});
 if(!process.env.QURAN_QA_URL){served=root;await p.evaluate(async()=>{await(await navigator.serviceWorker.getRegistration()).update()});await p.waitForFunction(async()=>{const keys=await caches.keys();return keys.length===1&&keys[0]==='uwa-bacaan-harian-v262-recent-surahs'})}
 await p.reload();await p.locator('[data-app-view="allday"]').click();await p.waitForFunction(()=>document.querySelector('#allday-count-big').textContent==='1/2');
 assert.deepEqual(await p.evaluate(()=>Object.fromEntries(Object.keys(localStorage).filter(k=>k.startsWith('uwa-quran-checklist-v1')).map(k=>[k,localStorage.getItem(k)]))),oldState,'checklist/backup untouched by upgrade');
 assert.deepEqual(await p.evaluate(()=>JSON.parse(localStorage.getItem('uwa-quran-reader-v1')).bookmarks),['2:20']);assert.equal(await p.evaluate(()=>localStorage.getItem('uwa-quran-tajweed-v1')),'on');
 await p.locator('#quran-tab-library').click();await p.locator('[data-recent-surah="2"]').waitFor();assert.equal(await p.locator('.quran-recent-item').count(),1);assert.match(await p.locator('[data-recent-surah="2"]').innerText(),/Ayat 20/);
 assert.deepEqual(await p.evaluate(()=>JSON.parse(localStorage.getItem('uwa-quran-recent-v1-legacy-backup')).last),{surah:2,ayah:20,page:4,mode:'list'});
 await p.locator('[data-recent-surah="2"]').click();await p.waitForFunction(()=>document.querySelectorAll('#quran-verse-list .quran-verse').length===286);await p.waitForFunction(()=>{const r=document.querySelector('#quran-ayah-20').getBoundingClientRect();return r.top>=70&&r.top<130});
 await p.locator('#quran-settings-toggle').click();await p.locator('#quran-page-mode').click();await p.waitForFunction(()=>document.querySelector('#quran-mushaf-page .quran-simple-verse')&&document.querySelector('#quran-reader-status').textContent==='');await p.locator('#quran-script-uthmani').click();await p.waitForFunction(()=>!document.querySelector('#quran-classic-panel').hidden&&document.querySelector('#quran-classic-page .quran-page-folio')&&document.querySelector('#quran-reader-status').textContent==='');await p.locator('#quran-settings-close').click();await p.locator('#quran-back').click();
 const saved=await p.evaluate(()=>localStorage.getItem('uwa-quran-recent-v1'));await p.waitForFunction(async()=>Boolean(await(await caches.open('uwa-bacaan-harian-v262-recent-surahs')).match('./quran/recent.js?v=262')));
 await ctx.setOffline(true);await p.reload();await p.locator('[data-app-view="allday"]').click();assert.equal(await p.locator('#allday-count-big').textContent(),'1/2');await p.locator('#quran-tab-library').click();assert.equal(await p.evaluate(()=>localStorage.getItem('uwa-quran-recent-v1')),saved);await p.locator('[data-recent-surah="2"]').click();await p.waitForFunction(()=>document.querySelector('#quran-classic-page .quran-page-folio')&&document.querySelector('#quran-reader-status').textContent==='');await p.evaluate(()=>document.fonts.ready);await p.screenshot({path:out+'/offline-classic-resume.png',fullPage:false});
 await p.locator('#quran-settings-toggle').click();await p.locator('#quran-list-mode').click();await p.waitForFunction(()=>document.querySelectorAll('#quran-verse-list .quran-verse').length===286);await p.locator('#quran-script-simple').click();await p.waitForFunction(()=>document.querySelector('#quran-script-simple').getAttribute('aria-pressed')==='true'&&document.querySelector('#quran-reader-status').textContent==='');await p.locator('#quran-page-mode').click();await p.waitForFunction(()=>document.querySelector('#quran-mushaf-page .quran-simple-verse')&&document.querySelector('#quran-reader-status').textContent==='');await p.locator('#quran-settings-close').click();await p.locator('#quran-back').click();
 const n=await ctx.newPage();await n.goto(url);await n.locator('[data-app-view="allday"]').click();await n.locator('#quran-tab-library').click();await n.locator('[data-recent-surah="2"]').click();await n.waitForFunction(()=>document.querySelector('#quran-mushaf-page .quran-simple-verse')&&document.querySelector('#quran-reader-status').textContent==='');
 // Uncached content is still network-dependent, and failed opening adds no history.
 const before=await n.evaluate(()=>localStorage.getItem('uwa-quran-recent-v1'));await n.locator('#quran-back').click();await n.locator('#quran-surah-list [data-surah="3"]').click();await n.waitForFunction(()=>document.querySelector('#quran-reader-status').textContent.includes('belum tersedia'));assert.equal(await n.evaluate(()=>localStorage.getItem('uwa-quran-recent-v1')),before);assert.deepEqual(errors,[]);
 const report={url,upgrade:!process.env.QURAN_QA_URL,checklistMigrationStatePreserved:true,legacySeedBackup:true,offlineHistory:true,cachedUthmaniSimpleListPageClassicResume:true,newOfflineTab:true,uncachedContentRequiresNetwork:true,uncachedFailureDoesNotRecord:true,cacheKeys:await p.evaluate(()=>caches.keys()),errors};assert.deepEqual(report.cacheKeys,['uwa-bacaan-harian-v262-recent-surahs']);fs.writeFileSync(out+'/recent-pwa.json',JSON.stringify(report,null,2));console.log('PASS',JSON.stringify(report));await b.close();server.close();
})().catch(e=>{console.error(e);server.close();process.exit(1)});
