const {chromium}=require('playwright'),assert=require('assert'),fs=require('fs'),path=require('path'),http=require('http');
const root=path.resolve(__dirname,'..'),baseline=process.env.QURAN_QA_BASELINE||'/private/tmp/quran-v263-baseline',out=process.env.QURAN_QA_OUTPUT||'/Users/halimi_hanim/Projects/Islamic-App-QA-V2.6.3';fs.mkdirSync(out,{recursive:true});let served=baseline;const mime={'.html':'text/html','.js':'text/javascript','.json':'application/json','.css':'text/css','.ttf':'font/ttf','.png':'image/png','.webmanifest':'application/manifest+json'};
const server=http.createServer((req,res)=>{const pn=decodeURIComponent(new URL(req.url,'http://localhost').pathname),file=path.join(served,pn==='/'?'index.html':pn);if(!file.startsWith(served+path.sep)){res.writeHead(403).end();return}try{res.writeHead(200,{'Content-Type':mime[path.extname(file)]||'application/octet-stream','Cache-Control':'no-store'});res.end(fs.readFileSync(file))}catch{res.writeHead(404).end()}});
(async()=>{await new Promise(r=>server.listen(8828,'127.0.0.1',r));const url=process.env.QURAN_QA_URL||'http://127.0.0.1:8828/';const b=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});try{const c=await b.newContext({viewport:{width:390,height:844},timezoneId:'Asia/Kuala_Lumpur'}),p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error'&&!m.text().startsWith('Failed to load resource:'))errors.push(m.text())});await p.goto(url);await p.evaluate(()=>navigator.serviceWorker.ready);await p.waitForFunction(()=>navigator.serviceWorker.controller);if(!process.env.QURAN_QA_URL)assert.deepEqual(await p.evaluate(()=>caches.keys()),['uwa-bacaan-harian-v262-recent-surahs']);
const original=await p.evaluate(()=>{const d=new Date(),day=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;localStorage.setItem('uwa-quran-checklist-v1-members','["112","114"]');localStorage.setItem('uwa-quran-checklist-v1-order','["114","112"]');localStorage.setItem('uwa-quran-checklist-v1-daily-'+day,'["112"]');localStorage.setItem('uwa-quran-checklist-v1-backup','synthetic-original');localStorage.setItem('uwa-quran-reader-v1',JSON.stringify({bookmarks:['2:20','114:6'],mode:'classic',script:'uthmani',uthmaniMode:'classic',last:{surah:113,ayah:1,page:604,mode:'classic'}}));localStorage.setItem('uwa-quran-recent-v1',JSON.stringify({schema:1,entries:[{surah:113,ayah:1,page:604,mode:'classic'}]}));localStorage.setItem('uwa-quran-recent-v1-legacy-backup',JSON.stringify({schema:1,last:{surah:113,ayah:1,page:604,mode:'classic'}}));localStorage.setItem('uwa-quran-tajweed-v1','on');return Object.fromEntries(Object.keys(localStorage).filter(k=>k.startsWith('uwa-quran-')).map(k=>[k,localStorage.getItem(k)]))});
if(!process.env.QURAN_QA_URL){served=root;await p.evaluate(async()=>{await(await navigator.serviceWorker.getRegistration()).update()});await p.waitForFunction(async()=>{const keys=await caches.keys();return keys.length===1&&keys[0]==='uwa-bacaan-harian-v263-favourite-excerpts'})}
await p.reload();await p.locator('[data-app-view="allday"]').click();await p.waitForFunction(()=>document.querySelectorAll('#quran-favourites-list .quran-verse-arabic').length===2);assert.deepEqual(await p.evaluate(()=>Object.fromEntries(Object.keys(localStorage).filter(k=>k.startsWith('uwa-quran-')).map(k=>[k,localStorage.getItem(k)]))),original,'upgrade/render preserves every saved Quran key');assert.equal(await p.locator('#allday-count-big').innerText(),'1/2');
// Warm Simple from the exact saved Uthmani List anchor using existing settings.
await p.locator('[data-favourite-open="2:20"]').click();await p.waitForFunction(()=>document.querySelectorAll('#quran-verse-list .quran-verse').length===286);await p.waitForFunction(()=>{const r=document.querySelector('#quran-ayah-20').getBoundingClientRect();return r.top>=70&&r.top<130});await p.locator('#quran-settings-toggle').click();await p.locator('#quran-script-simple').click();await p.waitForFunction(()=>document.querySelector('#quran-script-simple').getAttribute('aria-pressed')==='true'&&document.querySelector('#quran-reader-status').textContent==='');await p.locator('#quran-settings-close').click();await p.locator('#quran-back').click();await p.waitForFunction(()=>document.querySelectorAll('#quran-favourites-list .quran-verse-arabic').length===2);const saved=await p.evaluate(()=>localStorage.getItem('uwa-quran-reader-v1'));
await c.setOffline(true);await p.reload();await p.locator('[data-app-view="allday"]').click();await p.waitForFunction(()=>document.querySelectorAll('#quran-favourites-list .quran-verse-arabic').length===2);assert.equal(await p.evaluate(()=>localStorage.getItem('uwa-quran-reader-v1')),saved);await p.locator('#quran-favourites').scrollIntoViewIfNeeded();await p.screenshot({path:out+'/offline-favourites-390.png',fullPage:false});await p.locator('[data-favourite-open="2:20"]').click();await p.waitForFunction(()=>{const r=document.querySelector('#quran-ayah-20')?.getBoundingClientRect();return r&&r.top>=70&&r.top<130});await p.locator('#quran-settings-toggle').click();await p.locator('#quran-script-uthmani').click();await p.waitForFunction(()=>document.querySelector('#quran-script-uthmani').getAttribute('aria-pressed')==='true'&&document.querySelector('#quran-reader-status').textContent==='');await p.locator('#quran-settings-close').click();await p.locator('#quran-back').click();await p.waitForFunction(()=>document.querySelectorAll('#quran-favourites-list .quran-verse-arabic').length===2);
// New offline tab retains content/reference and exact-ayah navigation.
const n=await c.newPage();await n.goto(url);await n.locator('[data-app-view="allday"]').click();await n.waitForFunction(()=>document.querySelectorAll('#quran-favourites-list .quran-verse-arabic').length===2);await n.locator('[data-favourite-open="114:6"]').click();await n.waitForFunction(()=>document.querySelectorAll('#quran-verse-list .quran-verse').length===6);await n.locator('#quran-back').click();
// Uncached offline content keeps reference and removal. Opening fails gracefully, without false history.
await n.evaluate(()=>{const k='uwa-quran-reader-v1',d=JSON.parse(localStorage.getItem(k));d.bookmarks.push('3:1');localStorage.setItem(k,JSON.stringify(d))});await n.reload();await n.locator('[data-app-view="allday"]').click();await n.waitForFunction(()=>document.querySelector('[data-favourite="3:1"] [data-favourite-retry]'));assert.deepEqual(await n.evaluate(()=>JSON.parse(localStorage.getItem('uwa-quran-reader-v1')).bookmarks),['2:20','114:6','3:1']);const beforeHistory=await n.evaluate(()=>localStorage.getItem('uwa-quran-recent-v1'));await n.locator('[data-favourite-open="3:1"]').click();await n.waitForFunction(()=>document.querySelector('#quran-reader-status').textContent.includes('belum tersedia'));assert.equal(await n.evaluate(()=>localStorage.getItem('uwa-quran-recent-v1')),beforeHistory);await n.locator('#quran-back').click();await n.locator('[data-favourite-remove="3:1"]').click();assert.deepEqual(await n.evaluate(()=>JSON.parse(localStorage.getItem('uwa-quran-reader-v1')).bookmarks),['2:20','114:6']);await n.evaluate(async()=>{await(await navigator.serviceWorker.getRegistration()).update().catch(()=>{})});
const report={url,upgrade:!process.env.QURAN_QA_URL,allQuranStoragePreserved:true,offlineBothScripts:true,cachedExactAyahOpen:true,newOfflineTab:true,uncachedKeepsReferenceAndRemove:true,failedOpenNoHistory:true,cacheKeys:await n.evaluate(()=>caches.keys()),errors};assert.deepEqual(report.cacheKeys,['uwa-bacaan-harian-v263-favourite-excerpts']);assert.deepEqual(errors,[]);fs.writeFileSync(out+'/favourites-pwa.json',JSON.stringify(report,null,2));console.log('PASS',JSON.stringify(report))}finally{await b.close();server.close()}})().catch(e=>{console.error(e);server.close();process.exit(1)});
