const {chromium}=require('playwright'),assert=require('assert'),fs=require('fs'),path=require('path');
const root=path.resolve(__dirname,'..'),out=process.env.QURAN_QA_OUTPUT||'/Users/halimi_hanim/Projects/Islamic-App-QA-V2.6.3',url=process.env.QURAN_QA_URL||'http://127.0.0.1:8826/',key='uwa-quran-reader-v1',history='uwa-quran-recent-v1';fs.mkdirSync(out,{recursive:true});
const source=(s,script='uthmani')=>JSON.parse(fs.readFileSync(root+(script==='simple'?'/quran/scripts/simple/surah/':'/quran/surah/')+String(s).padStart(3,'0')+'.json'));
(async()=>{const b=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true}),report=[];
for(const width of [320,390,1280]){
 const c=await b.newContext({viewport:{width,height:844},serviceWorkers:'block',timezoneId:'Asia/Kuala_Lumpur'}),p=await c.newPage(),errors=[],requests=[];p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error')errors.push(m.text())});p.on('request',r=>requests.push(r.url()));
 await p.goto(url);await p.waitForFunction(()=>document.querySelectorAll('#quran-surah-list button').length===114);
 assert.equal(requests.filter(u=>/\/quran\/(surah|pages|scripts|tajweed)\//.test(u)).length,0,'lazy startup');
 await p.locator('[data-app-view="allday"]').click();await p.locator('#quran-favourites-empty').waitFor({state:'visible'});assert.match(await p.locator('#quran-favourites-empty').innerText(),/Belum ada petikan kegemaran/);await p.screenshot({path:out+`/favourites-empty-${width}.png`,fullPage:true});
 const seed=['1:1','2:255','28:3','114:6'];await p.evaluate(({key,history,seed})=>{localStorage.setItem(key,JSON.stringify({bookmarks:seed,mode:'classic',script:'uthmani',uthmaniMode:'classic',last:{surah:113,ayah:1,page:604,mode:'classic'},unknown:'keep'}));localStorage.setItem(history,JSON.stringify({schema:1,entries:[{surah:113,ayah:1,page:604,mode:'classic'}]}))},{key,history,seed});await p.reload();
 await p.locator('[data-app-view="allday"]').click();await p.waitForFunction(()=>document.querySelectorAll('#quran-favourites-list .quran-verse-arabic').length===4);
 assert.deepEqual(await p.locator('.quran-favourite').evaluateAll(es=>es.map(e=>e.dataset.favourite)),seed.slice().reverse());
 for(const ref of seed){const[s,a]=ref.split(':').map(Number),data=source(s).verses[a-1],card=p.locator(`[data-favourite="${ref}"]`);assert.equal(await card.locator('.quran-verse-arabic').innerText(),data[1]);assert.equal(await card.locator('.quran-verse-translation').innerText(),data[2])}
 const prior=await p.evaluate(history=>localStorage.getItem(history),history);assert.deepEqual(await p.evaluate(key=>JSON.parse(localStorage.getItem(key)).bookmarks,key),seed);
 assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);assert.equal(await p.locator('#quran-favourites input[type=checkbox]').count(),0);await p.screenshot({path:out+`/favourites-populated-${width}.png`,fullPage:true});
 // Reference opens exact ayah in full List, records once; Back returns same scroll/focus.
 const open=p.locator('[data-favourite-open="2:255"]');await open.scrollIntoViewIfNeeded();const backTop=await p.evaluate(()=>scrollY);await open.click();await p.waitForFunction(()=>document.querySelectorAll('#quran-verse-list .quran-verse').length===286);await p.waitForFunction(()=>{const r=document.querySelector('#quran-ayah-255').getBoundingClientRect();return r.top>=70&&r.top<130});
 let entries=await p.evaluate(history=>JSON.parse(localStorage.getItem(history)).entries,history);assert.equal(entries[0].surah,2);assert.equal(entries[0].ayah,255);assert.equal(entries[0].mode,'list');assert.equal(entries.length,2);
 const saved=p.locator('[data-bookmark="2:255"]');assert.equal(await saved.getAttribute('aria-pressed'),'true');const reading=await p.evaluate(history=>localStorage.getItem(history),history);await saved.click();assert.equal(await saved.getAttribute('aria-pressed'),'false');assert.equal(await p.evaluate(history=>localStorage.getItem(history),history),reading,'unsave does not fabricate reading');await saved.click();assert.equal(await saved.getAttribute('aria-pressed'),'true');assert.equal(await p.evaluate(history=>localStorage.getItem(history),history),reading);assert.equal(await p.evaluate(key=>JSON.parse(localStorage.getItem(key)).unknown,key),'keep');
 await p.locator('#quran-back').click();await p.waitForFunction(()=>document.activeElement?.dataset.favouriteOpen==='2:255');assert(Math.abs(await p.evaluate(()=>scrollY)-backTop)<3,'Back scroll');assert.equal(await p.locator('.quran-favourite').first().getAttribute('data-favourite'),'2:255');
 // Removal is a separate action and doesn't open/read.
 const beforeRemove=await p.evaluate(history=>localStorage.getItem(history),history);await p.locator('[data-favourite-remove="28:3"]').click();assert.equal(await p.locator('[data-favourite="28:3"]').count(),0);assert.equal(await p.locator('#quran-reader').isVisible(),false);assert.equal(await p.evaluate(history=>localStorage.getItem(history),history),beforeRemove);
 // Storage refusal never claims saved; recovery allows retry.
 await p.locator('[data-favourite-open="1:1"]').click();await p.waitForFunction(()=>document.querySelectorAll('#quran-verse-list .quran-verse').length===7);await p.waitForFunction(()=>document.querySelector('#quran-ayah-1').getBoundingClientRect().top>=70&&document.querySelector('#quran-ayah-1').getBoundingClientRect().top<130);
 await p.evaluate(()=>{window.qaSet=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k==='uwa-quran-reader-v1')throw Error('synthetic refusal');return window.qaSet.call(this,k,v)}});const button=p.locator('[data-bookmark="1:2"]');await button.click();assert.equal(await button.getAttribute('aria-pressed'),'false');assert.match(await p.locator('#quran-bookmark-status').innerText(),/gagal/);await p.evaluate(()=>Storage.prototype.setItem=window.qaSet);await button.click();assert.equal(await button.getAttribute('aria-pressed'),'true');
 // Script switch + global Tajweed preserved; card uses exact Simple, no fabricated colouring.
 await p.locator('#quran-settings-toggle').click();await p.locator('#quran-tajweed-on').click();await p.locator('#quran-script-simple').click();await p.waitForFunction(()=>document.querySelector('#quran-script-simple').getAttribute('aria-pressed')==='true'&&document.querySelector('#quran-reader-status').textContent==='');await p.locator('#quran-settings-close').click();await p.locator('#quran-back').click();await p.waitForFunction(()=>document.querySelector('[data-favourite="1:2"] .quran-verse-arabic')?.textContent===document.querySelector('[data-favourite="1:2"] .quran-verse-arabic')?.textContent&&document.querySelectorAll('#quran-favourites-list .quran-verse-arabic').length===4);
 assert.equal(await p.locator('[data-favourite="1:2"] .quran-verse-arabic').innerText(),source(1,'simple').verses[1][1]);assert.equal(await p.locator('#quran-favourites [class^="tajweed-"]').count(),0);assert.equal(await p.evaluate(()=>localStorage.getItem('uwa-quran-tajweed-v1')),'on');await p.screenshot({path:out+`/favourites-simple-${width}.png`,fullPage:true});
 const persisted=await p.evaluate(key=>JSON.parse(localStorage.getItem(key)).bookmarks,key);await p.reload();await p.locator('[data-app-view="allday"]').click();await p.waitForFunction(()=>document.querySelectorAll('#quran-favourites-list .quran-verse-arabic').length===4);assert.deepEqual(await p.evaluate(key=>JSON.parse(localStorage.getItem(key)).bookmarks,key),persisted);
 // Day rollover has no favourite mutation.
 await p.clock.install({time:new Date('2026-10-04T15:59:58Z')});await p.clock.fastForward(3000);await p.reload();await p.locator('[data-app-view="allday"]').click();assert.deepEqual(await p.evaluate(key=>JSON.parse(localStorage.getItem(key)).bookmarks,key),persisted);
 // Many same-surah favourites: progressive content, grouped requests, no cap.
 const many=Array.from({length:25},(_,i)=>`2:${i+1}`);await p.evaluate(({key,many})=>{const d=JSON.parse(localStorage.getItem(key));d.bookmarks=many;d.script='uthmani';localStorage.setItem(key,JSON.stringify(d))},{key,many});await p.reload();const start=requests.length;await p.locator('[data-app-view="allday"]').click();await p.waitForFunction(()=>document.querySelectorAll('#quran-favourites-list .quran-verse-arabic').length===10);await p.locator('#quran-favourites-more').click();await p.waitForFunction(()=>document.querySelectorAll('#quran-favourites-list .quran-verse-arabic').length===20);await p.locator('#quran-favourites-more').click();await p.waitForFunction(()=>document.querySelectorAll('#quran-favourites-list .quran-verse-arabic').length===25);assert.equal(await p.locator('#quran-favourites-more').isVisible(),false);assert.equal(requests.slice(start).filter(u=>/\/quran\/surah\/002.json/.test(u)).length,1,'group/cache reuse');assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 // Mixed invalid evidence isn't touched on display; mutation backs it up.
 const mixed=['1:1','bad','0:1','114:7','114:6','01:001'];await p.evaluate(({key,mixed})=>{const d=JSON.parse(localStorage.getItem(key));d.bookmarks=mixed;localStorage.setItem(key,JSON.stringify(d))},{key,mixed});await p.reload();await p.locator('[data-app-view="allday"]').click();await p.waitForFunction(()=>document.querySelectorAll('.quran-favourite').length===2);assert.deepEqual(await p.evaluate(key=>JSON.parse(localStorage.getItem(key)).bookmarks,key),mixed);await p.locator('[data-favourite-remove="114:6"]').click();assert.deepEqual(await p.evaluate(key=>JSON.parse(localStorage.getItem(key+'-bookmarks-backup-v263')).bookmarks,key),mixed);assert.deepEqual(await p.evaluate(key=>JSON.parse(localStorage.getItem(key)).bookmarks,key),['1:1']);assert.deepEqual(errors,[]);
 report.push({width,legacyPreserved:true,exactBothScriptsAndMeaning:true,saveUnsaveRemoveResave:true,headerSafeOpenBackFocusScroll:true,recentHistoryIsolation:true,storageRefusalRecovery:true,reloadDayPersistence:true,progressive25GroupedRequest:true,invalidEvidenceBackup:true,startupQuranRequests:0,errors:0});await c.close();console.log('passed width',width);
}
// Slow loading, removal, rapid navigation and content failure preserve references.
const c=await b.newContext({viewport:{width:390,height:844},serviceWorkers:'block'}),p=await c.newPage(),edgeErrors=[];p.on('pageerror',e=>edgeErrors.push(e.message));p.on('console',m=>{if(m.type()==='error'&&!m.text().startsWith('Failed to load resource:'))edgeErrors.push(m.text())});await p.goto(url);await p.evaluate(key=>localStorage.setItem(key,JSON.stringify({bookmarks:['28:3','2:255'],script:'uthmani',mode:'list'})),key);await p.reload();let release;const gate=new Promise(r=>release=r);await p.route('**/quran/surah/*.json',async route=>{await gate;await route.continue()});await p.locator('[data-app-view="allday"]').click();await p.locator('.quran-favourite-loading').first().waitFor();await p.screenshot({path:out+'/favourites-loading-390.png',fullPage:true});await p.locator('[data-favourite-remove="28:3"]').click();await p.locator('#quran-tab-library').click();release();await p.waitForTimeout(300);assert.equal(await p.locator('[data-favourite="28:3"]').count(),0);await p.unroute('**/quran/surah/*.json');await p.locator('#quran-tab-routine').click();await p.waitForFunction(()=>document.querySelector('[data-favourite="2:255"] .quran-verse-arabic'));
await p.evaluate(key=>{const d=JSON.parse(localStorage.getItem(key));d.bookmarks=['3:1'];localStorage.setItem(key,JSON.stringify(d))},key);await p.reload();await p.route('**/quran/surah/003.json',r=>r.fulfill({status:503,body:'unavailable'}));await p.locator('[data-app-view="allday"]').click();await p.waitForFunction(()=>document.querySelector('[data-favourite-retry]'));assert.equal(await p.locator('[data-favourite-remove="3:1"]').count(),1);assert.deepEqual(await p.evaluate(key=>JSON.parse(localStorage.getItem(key)).bookmarks,key),['3:1']);await p.screenshot({path:out+'/favourites-error-390.png',fullPage:true});await p.unroute('**/quran/surah/003.json');await p.locator('[data-favourite-retry]').click();await p.waitForFunction(()=>document.querySelector('[data-favourite="3:1"] .quran-verse-arabic'));assert.deepEqual(edgeErrors,[]);await c.close();await b.close();fs.writeFileSync(out+'/favourites-interactions.json',JSON.stringify({widths:report,staleLoadRemovalNavigation:true,fetchFailureRetryPreservesReferences:true,physicalIPhoneTested:false},null,2));console.log('PASS favourites browser');
})().catch(e=>{console.error(e);process.exit(1)});
